// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fluorite_wire.proto
// Protobuf Java Version: 4.33.4

package io.fluorite.sdk.proto;

@com.google.protobuf.Generated
public interface AppendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fluorite.wire.AppendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes writer_id = 1;</code>
   * @return The writerId.
   */
  com.google.protobuf.ByteString getWriterId();

  /**
   * <code>uint64 append_seq = 2;</code>
   * @return The appendSeq.
   */
  long getAppendSeq();

  /**
   * <code>repeated .fluorite.wire.RecordBatch batches = 3;</code>
   */
  java.util.List<io.fluorite.sdk.proto.RecordBatch> 
      getBatchesList();
  /**
   * <code>repeated .fluorite.wire.RecordBatch batches = 3;</code>
   */
  io.fluorite.sdk.proto.RecordBatch getBatches(int index);
  /**
   * <code>repeated .fluorite.wire.RecordBatch batches = 3;</code>
   */
  int getBatchesCount();
  /**
   * <code>repeated .fluorite.wire.RecordBatch batches = 3;</code>
   */
  java.util.List<? extends io.fluorite.sdk.proto.RecordBatchOrBuilder> 
      getBatchesOrBuilderList();
  /**
   * <code>repeated .fluorite.wire.RecordBatch batches = 3;</code>
   */
  io.fluorite.sdk.proto.RecordBatchOrBuilder getBatchesOrBuilder(
      int index);
}
