// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fluorite_wire.proto
// Protobuf Java Version: 4.33.4

package io.fluorite.sdk.proto;

@com.google.protobuf.Generated
public interface AuthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fluorite.wire.AuthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>uint32 error_code = 2;</code>
   * @return The errorCode.
   */
  int getErrorCode();

  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
