// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fluorite_wire.proto
// Protobuf Java Version: 4.33.4

package io.fluorite.sdk.proto;

/**
 * Protobuf enum {@code fluorite.wire.HeartbeatStatus}
 */
@com.google.protobuf.Generated
public enum HeartbeatStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>HEARTBEAT_STATUS_OK = 0;</code>
   */
  HEARTBEAT_STATUS_OK(0),
  /**
   * <code>HEARTBEAT_STATUS_UNKNOWN_MEMBER = 1;</code>
   */
  HEARTBEAT_STATUS_UNKNOWN_MEMBER(1),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "HeartbeatStatus");
  }
  /**
   * <code>HEARTBEAT_STATUS_OK = 0;</code>
   */
  public static final int HEARTBEAT_STATUS_OK_VALUE = 0;
  /**
   * <code>HEARTBEAT_STATUS_UNKNOWN_MEMBER = 1;</code>
   */
  public static final int HEARTBEAT_STATUS_UNKNOWN_MEMBER_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static HeartbeatStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static HeartbeatStatus forNumber(int value) {
    switch (value) {
      case 0: return HEARTBEAT_STATUS_OK;
      case 1: return HEARTBEAT_STATUS_UNKNOWN_MEMBER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<HeartbeatStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      HeartbeatStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<HeartbeatStatus>() {
          public HeartbeatStatus findValueByNumber(int number) {
            return HeartbeatStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.fluorite.sdk.proto.FluoriteWire.getDescriptor().getEnumTypes().get(0);
  }

  private static final HeartbeatStatus[] VALUES = values();

  public static HeartbeatStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private HeartbeatStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fluorite.wire.HeartbeatStatus)
}

