// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fluorite_wire.proto
// Protobuf Java Version: 4.33.4

package io.fluorite.sdk.proto;

/**
 * Protobuf type {@code fluorite.wire.RecordBatch}
 */
@com.google.protobuf.Generated
public final class RecordBatch extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:fluorite.wire.RecordBatch)
    RecordBatchOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "RecordBatch");
  }
  // Use RecordBatch.newBuilder() to construct.
  private RecordBatch(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RecordBatch() {
    records_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.fluorite.sdk.proto.FluoriteWire.internal_static_fluorite_wire_RecordBatch_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.fluorite.sdk.proto.FluoriteWire.internal_static_fluorite_wire_RecordBatch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.fluorite.sdk.proto.RecordBatch.class, io.fluorite.sdk.proto.RecordBatch.Builder.class);
  }

  public static final int TOPIC_ID_FIELD_NUMBER = 1;
  private int topicId_ = 0;
  /**
   * <code>uint32 topic_id = 1;</code>
   * @return The topicId.
   */
  @java.lang.Override
  public int getTopicId() {
    return topicId_;
  }

  public static final int SCHEMA_ID_FIELD_NUMBER = 2;
  private int schemaId_ = 0;
  /**
   * <code>uint32 schema_id = 2;</code>
   * @return The schemaId.
   */
  @java.lang.Override
  public int getSchemaId() {
    return schemaId_;
  }

  public static final int RECORDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<io.fluorite.sdk.proto.Record> records_;
  /**
   * <code>repeated .fluorite.wire.Record records = 3;</code>
   */
  @java.lang.Override
  public java.util.List<io.fluorite.sdk.proto.Record> getRecordsList() {
    return records_;
  }
  /**
   * <code>repeated .fluorite.wire.Record records = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.fluorite.sdk.proto.RecordOrBuilder> 
      getRecordsOrBuilderList() {
    return records_;
  }
  /**
   * <code>repeated .fluorite.wire.Record records = 3;</code>
   */
  @java.lang.Override
  public int getRecordsCount() {
    return records_.size();
  }
  /**
   * <code>repeated .fluorite.wire.Record records = 3;</code>
   */
  @java.lang.Override
  public io.fluorite.sdk.proto.Record getRecords(int index) {
    return records_.get(index);
  }
  /**
   * <code>repeated .fluorite.wire.Record records = 3;</code>
   */
  @java.lang.Override
  public io.fluorite.sdk.proto.RecordOrBuilder getRecordsOrBuilder(
      int index) {
    return records_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (topicId_ != 0) {
      output.writeUInt32(1, topicId_);
    }
    if (schemaId_ != 0) {
      output.writeUInt32(2, schemaId_);
    }
    for (int i = 0; i < records_.size(); i++) {
      output.writeMessage(3, records_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (topicId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, topicId_);
    }
    if (schemaId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, schemaId_);
    }
    for (int i = 0; i < records_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, records_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.fluorite.sdk.proto.RecordBatch)) {
      return super.equals(obj);
    }
    io.fluorite.sdk.proto.RecordBatch other = (io.fluorite.sdk.proto.RecordBatch) obj;

    if (getTopicId()
        != other.getTopicId()) return false;
    if (getSchemaId()
        != other.getSchemaId()) return false;
    if (!getRecordsList()
        .equals(other.getRecordsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPIC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTopicId();
    hash = (37 * hash) + SCHEMA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaId();
    if (getRecordsCount() > 0) {
      hash = (37 * hash) + RECORDS_FIELD_NUMBER;
      hash = (53 * hash) + getRecordsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.fluorite.sdk.proto.RecordBatch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.fluorite.sdk.proto.RecordBatch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.fluorite.sdk.proto.RecordBatch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.fluorite.sdk.proto.RecordBatch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.fluorite.sdk.proto.RecordBatch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.fluorite.sdk.proto.RecordBatch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.fluorite.sdk.proto.RecordBatch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.fluorite.sdk.proto.RecordBatch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.fluorite.sdk.proto.RecordBatch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.fluorite.sdk.proto.RecordBatch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.fluorite.sdk.proto.RecordBatch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.fluorite.sdk.proto.RecordBatch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.fluorite.sdk.proto.RecordBatch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fluorite.wire.RecordBatch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fluorite.wire.RecordBatch)
      io.fluorite.sdk.proto.RecordBatchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.fluorite.sdk.proto.FluoriteWire.internal_static_fluorite_wire_RecordBatch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.fluorite.sdk.proto.FluoriteWire.internal_static_fluorite_wire_RecordBatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.fluorite.sdk.proto.RecordBatch.class, io.fluorite.sdk.proto.RecordBatch.Builder.class);
    }

    // Construct using io.fluorite.sdk.proto.RecordBatch.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      topicId_ = 0;
      schemaId_ = 0;
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
      } else {
        records_ = null;
        recordsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.fluorite.sdk.proto.FluoriteWire.internal_static_fluorite_wire_RecordBatch_descriptor;
    }

    @java.lang.Override
    public io.fluorite.sdk.proto.RecordBatch getDefaultInstanceForType() {
      return io.fluorite.sdk.proto.RecordBatch.getDefaultInstance();
    }

    @java.lang.Override
    public io.fluorite.sdk.proto.RecordBatch build() {
      io.fluorite.sdk.proto.RecordBatch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.fluorite.sdk.proto.RecordBatch buildPartial() {
      io.fluorite.sdk.proto.RecordBatch result = new io.fluorite.sdk.proto.RecordBatch(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.fluorite.sdk.proto.RecordBatch result) {
      if (recordsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          records_ = java.util.Collections.unmodifiableList(records_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.records_ = records_;
      } else {
        result.records_ = recordsBuilder_.build();
      }
    }

    private void buildPartial0(io.fluorite.sdk.proto.RecordBatch result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.topicId_ = topicId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.schemaId_ = schemaId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.fluorite.sdk.proto.RecordBatch) {
        return mergeFrom((io.fluorite.sdk.proto.RecordBatch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.fluorite.sdk.proto.RecordBatch other) {
      if (other == io.fluorite.sdk.proto.RecordBatch.getDefaultInstance()) return this;
      if (other.getTopicId() != 0) {
        setTopicId(other.getTopicId());
      }
      if (other.getSchemaId() != 0) {
        setSchemaId(other.getSchemaId());
      }
      if (recordsBuilder_ == null) {
        if (!other.records_.isEmpty()) {
          if (records_.isEmpty()) {
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRecordsIsMutable();
            records_.addAll(other.records_);
          }
          onChanged();
        }
      } else {
        if (!other.records_.isEmpty()) {
          if (recordsBuilder_.isEmpty()) {
            recordsBuilder_.dispose();
            recordsBuilder_ = null;
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000004);
            recordsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetRecordsFieldBuilder() : null;
          } else {
            recordsBuilder_.addAllMessages(other.records_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              topicId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              schemaId_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              io.fluorite.sdk.proto.Record m =
                  input.readMessage(
                      io.fluorite.sdk.proto.Record.parser(),
                      extensionRegistry);
              if (recordsBuilder_ == null) {
                ensureRecordsIsMutable();
                records_.add(m);
              } else {
                recordsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int topicId_ ;
    /**
     * <code>uint32 topic_id = 1;</code>
     * @return The topicId.
     */
    @java.lang.Override
    public int getTopicId() {
      return topicId_;
    }
    /**
     * <code>uint32 topic_id = 1;</code>
     * @param value The topicId to set.
     * @return This builder for chaining.
     */
    public Builder setTopicId(int value) {

      topicId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 topic_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopicId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      topicId_ = 0;
      onChanged();
      return this;
    }

    private int schemaId_ ;
    /**
     * <code>uint32 schema_id = 2;</code>
     * @return The schemaId.
     */
    @java.lang.Override
    public int getSchemaId() {
      return schemaId_;
    }
    /**
     * <code>uint32 schema_id = 2;</code>
     * @param value The schemaId to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaId(int value) {

      schemaId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 schema_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      schemaId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<io.fluorite.sdk.proto.Record> records_ =
      java.util.Collections.emptyList();
    private void ensureRecordsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        records_ = new java.util.ArrayList<io.fluorite.sdk.proto.Record>(records_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.fluorite.sdk.proto.Record, io.fluorite.sdk.proto.Record.Builder, io.fluorite.sdk.proto.RecordOrBuilder> recordsBuilder_;

    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public java.util.List<io.fluorite.sdk.proto.Record> getRecordsList() {
      if (recordsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(records_);
      } else {
        return recordsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public int getRecordsCount() {
      if (recordsBuilder_ == null) {
        return records_.size();
      } else {
        return recordsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public io.fluorite.sdk.proto.Record getRecords(int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);
      } else {
        return recordsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public Builder setRecords(
        int index, io.fluorite.sdk.proto.Record value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.set(index, value);
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public Builder setRecords(
        int index, io.fluorite.sdk.proto.Record.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.set(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public Builder addRecords(io.fluorite.sdk.proto.Record value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public Builder addRecords(
        int index, io.fluorite.sdk.proto.Record value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(index, value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public Builder addRecords(
        io.fluorite.sdk.proto.Record.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public Builder addRecords(
        int index, io.fluorite.sdk.proto.Record.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public Builder addAllRecords(
        java.lang.Iterable<? extends io.fluorite.sdk.proto.Record> values) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, records_);
        onChanged();
      } else {
        recordsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public Builder clearRecords() {
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        recordsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public Builder removeRecords(int index) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.remove(index);
        onChanged();
      } else {
        recordsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public io.fluorite.sdk.proto.Record.Builder getRecordsBuilder(
        int index) {
      return internalGetRecordsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public io.fluorite.sdk.proto.RecordOrBuilder getRecordsOrBuilder(
        int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);  } else {
        return recordsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public java.util.List<? extends io.fluorite.sdk.proto.RecordOrBuilder> 
         getRecordsOrBuilderList() {
      if (recordsBuilder_ != null) {
        return recordsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(records_);
      }
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public io.fluorite.sdk.proto.Record.Builder addRecordsBuilder() {
      return internalGetRecordsFieldBuilder().addBuilder(
          io.fluorite.sdk.proto.Record.getDefaultInstance());
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public io.fluorite.sdk.proto.Record.Builder addRecordsBuilder(
        int index) {
      return internalGetRecordsFieldBuilder().addBuilder(
          index, io.fluorite.sdk.proto.Record.getDefaultInstance());
    }
    /**
     * <code>repeated .fluorite.wire.Record records = 3;</code>
     */
    public java.util.List<io.fluorite.sdk.proto.Record.Builder> 
         getRecordsBuilderList() {
      return internalGetRecordsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.fluorite.sdk.proto.Record, io.fluorite.sdk.proto.Record.Builder, io.fluorite.sdk.proto.RecordOrBuilder> 
        internalGetRecordsFieldBuilder() {
      if (recordsBuilder_ == null) {
        recordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.fluorite.sdk.proto.Record, io.fluorite.sdk.proto.Record.Builder, io.fluorite.sdk.proto.RecordOrBuilder>(
                records_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        records_ = null;
      }
      return recordsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:fluorite.wire.RecordBatch)
  }

  // @@protoc_insertion_point(class_scope:fluorite.wire.RecordBatch)
  private static final io.fluorite.sdk.proto.RecordBatch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.fluorite.sdk.proto.RecordBatch();
  }

  public static io.fluorite.sdk.proto.RecordBatch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecordBatch>
      PARSER = new com.google.protobuf.AbstractParser<RecordBatch>() {
    @java.lang.Override
    public RecordBatch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RecordBatch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecordBatch> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.fluorite.sdk.proto.RecordBatch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

