// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flourine_wire.proto
// Protobuf Java Version: 4.33.4

package io.flourine.sdk.proto;

/**
 * Protobuf type {@code flourine.wire.ClientMessage}
 */
@com.google.protobuf.Generated
public final class ClientMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flourine.wire.ClientMessage)
    ClientMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "ClientMessage");
  }
  // Use ClientMessage.newBuilder() to construct.
  private ClientMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ClientMessage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_ClientMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_ClientMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.flourine.sdk.proto.ClientMessage.class, io.flourine.sdk.proto.ClientMessage.Builder.class);
  }

  private int messageCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object message_;
  public enum MessageCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    APPEND(1),
    READ(2),
    JOIN_GROUP(3),
    HEARTBEAT(4),
    REJOIN(5),
    LEAVE_GROUP(6),
    COMMIT(7),
    AUTH(8),
    MESSAGE_NOT_SET(0);
    private final int value;
    private MessageCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageCase forNumber(int value) {
      switch (value) {
        case 1: return APPEND;
        case 2: return READ;
        case 3: return JOIN_GROUP;
        case 4: return HEARTBEAT;
        case 5: return REJOIN;
        case 6: return LEAVE_GROUP;
        case 7: return COMMIT;
        case 8: return AUTH;
        case 0: return MESSAGE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageCase
  getMessageCase() {
    return MessageCase.forNumber(
        messageCase_);
  }

  public static final int APPEND_FIELD_NUMBER = 1;
  /**
   * <code>.flourine.wire.AppendRequest append = 1;</code>
   * @return Whether the append field is set.
   */
  @java.lang.Override
  public boolean hasAppend() {
    return messageCase_ == 1;
  }
  /**
   * <code>.flourine.wire.AppendRequest append = 1;</code>
   * @return The append.
   */
  @java.lang.Override
  public io.flourine.sdk.proto.AppendRequest getAppend() {
    if (messageCase_ == 1) {
       return (io.flourine.sdk.proto.AppendRequest) message_;
    }
    return io.flourine.sdk.proto.AppendRequest.getDefaultInstance();
  }
  /**
   * <code>.flourine.wire.AppendRequest append = 1;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.AppendRequestOrBuilder getAppendOrBuilder() {
    if (messageCase_ == 1) {
       return (io.flourine.sdk.proto.AppendRequest) message_;
    }
    return io.flourine.sdk.proto.AppendRequest.getDefaultInstance();
  }

  public static final int READ_FIELD_NUMBER = 2;
  /**
   * <code>.flourine.wire.ReadRequest read = 2;</code>
   * @return Whether the read field is set.
   */
  @java.lang.Override
  public boolean hasRead() {
    return messageCase_ == 2;
  }
  /**
   * <code>.flourine.wire.ReadRequest read = 2;</code>
   * @return The read.
   */
  @java.lang.Override
  public io.flourine.sdk.proto.ReadRequest getRead() {
    if (messageCase_ == 2) {
       return (io.flourine.sdk.proto.ReadRequest) message_;
    }
    return io.flourine.sdk.proto.ReadRequest.getDefaultInstance();
  }
  /**
   * <code>.flourine.wire.ReadRequest read = 2;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.ReadRequestOrBuilder getReadOrBuilder() {
    if (messageCase_ == 2) {
       return (io.flourine.sdk.proto.ReadRequest) message_;
    }
    return io.flourine.sdk.proto.ReadRequest.getDefaultInstance();
  }

  public static final int JOIN_GROUP_FIELD_NUMBER = 3;
  /**
   * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
   * @return Whether the joinGroup field is set.
   */
  @java.lang.Override
  public boolean hasJoinGroup() {
    return messageCase_ == 3;
  }
  /**
   * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
   * @return The joinGroup.
   */
  @java.lang.Override
  public io.flourine.sdk.proto.JoinGroupRequest getJoinGroup() {
    if (messageCase_ == 3) {
       return (io.flourine.sdk.proto.JoinGroupRequest) message_;
    }
    return io.flourine.sdk.proto.JoinGroupRequest.getDefaultInstance();
  }
  /**
   * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.JoinGroupRequestOrBuilder getJoinGroupOrBuilder() {
    if (messageCase_ == 3) {
       return (io.flourine.sdk.proto.JoinGroupRequest) message_;
    }
    return io.flourine.sdk.proto.JoinGroupRequest.getDefaultInstance();
  }

  public static final int HEARTBEAT_FIELD_NUMBER = 4;
  /**
   * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
   * @return Whether the heartbeat field is set.
   */
  @java.lang.Override
  public boolean hasHeartbeat() {
    return messageCase_ == 4;
  }
  /**
   * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
   * @return The heartbeat.
   */
  @java.lang.Override
  public io.flourine.sdk.proto.HeartbeatRequest getHeartbeat() {
    if (messageCase_ == 4) {
       return (io.flourine.sdk.proto.HeartbeatRequest) message_;
    }
    return io.flourine.sdk.proto.HeartbeatRequest.getDefaultInstance();
  }
  /**
   * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.HeartbeatRequestOrBuilder getHeartbeatOrBuilder() {
    if (messageCase_ == 4) {
       return (io.flourine.sdk.proto.HeartbeatRequest) message_;
    }
    return io.flourine.sdk.proto.HeartbeatRequest.getDefaultInstance();
  }

  public static final int REJOIN_FIELD_NUMBER = 5;
  /**
   * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
   * @return Whether the rejoin field is set.
   */
  @java.lang.Override
  public boolean hasRejoin() {
    return messageCase_ == 5;
  }
  /**
   * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
   * @return The rejoin.
   */
  @java.lang.Override
  public io.flourine.sdk.proto.RejoinRequest getRejoin() {
    if (messageCase_ == 5) {
       return (io.flourine.sdk.proto.RejoinRequest) message_;
    }
    return io.flourine.sdk.proto.RejoinRequest.getDefaultInstance();
  }
  /**
   * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.RejoinRequestOrBuilder getRejoinOrBuilder() {
    if (messageCase_ == 5) {
       return (io.flourine.sdk.proto.RejoinRequest) message_;
    }
    return io.flourine.sdk.proto.RejoinRequest.getDefaultInstance();
  }

  public static final int LEAVE_GROUP_FIELD_NUMBER = 6;
  /**
   * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
   * @return Whether the leaveGroup field is set.
   */
  @java.lang.Override
  public boolean hasLeaveGroup() {
    return messageCase_ == 6;
  }
  /**
   * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
   * @return The leaveGroup.
   */
  @java.lang.Override
  public io.flourine.sdk.proto.LeaveGroupRequest getLeaveGroup() {
    if (messageCase_ == 6) {
       return (io.flourine.sdk.proto.LeaveGroupRequest) message_;
    }
    return io.flourine.sdk.proto.LeaveGroupRequest.getDefaultInstance();
  }
  /**
   * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.LeaveGroupRequestOrBuilder getLeaveGroupOrBuilder() {
    if (messageCase_ == 6) {
       return (io.flourine.sdk.proto.LeaveGroupRequest) message_;
    }
    return io.flourine.sdk.proto.LeaveGroupRequest.getDefaultInstance();
  }

  public static final int COMMIT_FIELD_NUMBER = 7;
  /**
   * <code>.flourine.wire.CommitRequest commit = 7;</code>
   * @return Whether the commit field is set.
   */
  @java.lang.Override
  public boolean hasCommit() {
    return messageCase_ == 7;
  }
  /**
   * <code>.flourine.wire.CommitRequest commit = 7;</code>
   * @return The commit.
   */
  @java.lang.Override
  public io.flourine.sdk.proto.CommitRequest getCommit() {
    if (messageCase_ == 7) {
       return (io.flourine.sdk.proto.CommitRequest) message_;
    }
    return io.flourine.sdk.proto.CommitRequest.getDefaultInstance();
  }
  /**
   * <code>.flourine.wire.CommitRequest commit = 7;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.CommitRequestOrBuilder getCommitOrBuilder() {
    if (messageCase_ == 7) {
       return (io.flourine.sdk.proto.CommitRequest) message_;
    }
    return io.flourine.sdk.proto.CommitRequest.getDefaultInstance();
  }

  public static final int AUTH_FIELD_NUMBER = 8;
  /**
   * <code>.flourine.wire.AuthRequest auth = 8;</code>
   * @return Whether the auth field is set.
   */
  @java.lang.Override
  public boolean hasAuth() {
    return messageCase_ == 8;
  }
  /**
   * <code>.flourine.wire.AuthRequest auth = 8;</code>
   * @return The auth.
   */
  @java.lang.Override
  public io.flourine.sdk.proto.AuthRequest getAuth() {
    if (messageCase_ == 8) {
       return (io.flourine.sdk.proto.AuthRequest) message_;
    }
    return io.flourine.sdk.proto.AuthRequest.getDefaultInstance();
  }
  /**
   * <code>.flourine.wire.AuthRequest auth = 8;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.AuthRequestOrBuilder getAuthOrBuilder() {
    if (messageCase_ == 8) {
       return (io.flourine.sdk.proto.AuthRequest) message_;
    }
    return io.flourine.sdk.proto.AuthRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageCase_ == 1) {
      output.writeMessage(1, (io.flourine.sdk.proto.AppendRequest) message_);
    }
    if (messageCase_ == 2) {
      output.writeMessage(2, (io.flourine.sdk.proto.ReadRequest) message_);
    }
    if (messageCase_ == 3) {
      output.writeMessage(3, (io.flourine.sdk.proto.JoinGroupRequest) message_);
    }
    if (messageCase_ == 4) {
      output.writeMessage(4, (io.flourine.sdk.proto.HeartbeatRequest) message_);
    }
    if (messageCase_ == 5) {
      output.writeMessage(5, (io.flourine.sdk.proto.RejoinRequest) message_);
    }
    if (messageCase_ == 6) {
      output.writeMessage(6, (io.flourine.sdk.proto.LeaveGroupRequest) message_);
    }
    if (messageCase_ == 7) {
      output.writeMessage(7, (io.flourine.sdk.proto.CommitRequest) message_);
    }
    if (messageCase_ == 8) {
      output.writeMessage(8, (io.flourine.sdk.proto.AuthRequest) message_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.flourine.sdk.proto.AppendRequest) message_);
    }
    if (messageCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.flourine.sdk.proto.ReadRequest) message_);
    }
    if (messageCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.flourine.sdk.proto.JoinGroupRequest) message_);
    }
    if (messageCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (io.flourine.sdk.proto.HeartbeatRequest) message_);
    }
    if (messageCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (io.flourine.sdk.proto.RejoinRequest) message_);
    }
    if (messageCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (io.flourine.sdk.proto.LeaveGroupRequest) message_);
    }
    if (messageCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (io.flourine.sdk.proto.CommitRequest) message_);
    }
    if (messageCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (io.flourine.sdk.proto.AuthRequest) message_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.flourine.sdk.proto.ClientMessage)) {
      return super.equals(obj);
    }
    io.flourine.sdk.proto.ClientMessage other = (io.flourine.sdk.proto.ClientMessage) obj;

    if (!getMessageCase().equals(other.getMessageCase())) return false;
    switch (messageCase_) {
      case 1:
        if (!getAppend()
            .equals(other.getAppend())) return false;
        break;
      case 2:
        if (!getRead()
            .equals(other.getRead())) return false;
        break;
      case 3:
        if (!getJoinGroup()
            .equals(other.getJoinGroup())) return false;
        break;
      case 4:
        if (!getHeartbeat()
            .equals(other.getHeartbeat())) return false;
        break;
      case 5:
        if (!getRejoin()
            .equals(other.getRejoin())) return false;
        break;
      case 6:
        if (!getLeaveGroup()
            .equals(other.getLeaveGroup())) return false;
        break;
      case 7:
        if (!getCommit()
            .equals(other.getCommit())) return false;
        break;
      case 8:
        if (!getAuth()
            .equals(other.getAuth())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (messageCase_) {
      case 1:
        hash = (37 * hash) + APPEND_FIELD_NUMBER;
        hash = (53 * hash) + getAppend().hashCode();
        break;
      case 2:
        hash = (37 * hash) + READ_FIELD_NUMBER;
        hash = (53 * hash) + getRead().hashCode();
        break;
      case 3:
        hash = (37 * hash) + JOIN_GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getJoinGroup().hashCode();
        break;
      case 4:
        hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeat().hashCode();
        break;
      case 5:
        hash = (37 * hash) + REJOIN_FIELD_NUMBER;
        hash = (53 * hash) + getRejoin().hashCode();
        break;
      case 6:
        hash = (37 * hash) + LEAVE_GROUP_FIELD_NUMBER;
        hash = (53 * hash) + getLeaveGroup().hashCode();
        break;
      case 7:
        hash = (37 * hash) + COMMIT_FIELD_NUMBER;
        hash = (53 * hash) + getCommit().hashCode();
        break;
      case 8:
        hash = (37 * hash) + AUTH_FIELD_NUMBER;
        hash = (53 * hash) + getAuth().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.flourine.sdk.proto.ClientMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.ClientMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.ClientMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.ClientMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.ClientMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.ClientMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.ClientMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flourine.sdk.proto.ClientMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.flourine.sdk.proto.ClientMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.flourine.sdk.proto.ClientMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.flourine.sdk.proto.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flourine.sdk.proto.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.flourine.sdk.proto.ClientMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code flourine.wire.ClientMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flourine.wire.ClientMessage)
      io.flourine.sdk.proto.ClientMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_ClientMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.flourine.sdk.proto.ClientMessage.class, io.flourine.sdk.proto.ClientMessage.Builder.class);
    }

    // Construct using io.flourine.sdk.proto.ClientMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (appendBuilder_ != null) {
        appendBuilder_.clear();
      }
      if (readBuilder_ != null) {
        readBuilder_.clear();
      }
      if (joinGroupBuilder_ != null) {
        joinGroupBuilder_.clear();
      }
      if (heartbeatBuilder_ != null) {
        heartbeatBuilder_.clear();
      }
      if (rejoinBuilder_ != null) {
        rejoinBuilder_.clear();
      }
      if (leaveGroupBuilder_ != null) {
        leaveGroupBuilder_.clear();
      }
      if (commitBuilder_ != null) {
        commitBuilder_.clear();
      }
      if (authBuilder_ != null) {
        authBuilder_.clear();
      }
      messageCase_ = 0;
      message_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_ClientMessage_descriptor;
    }

    @java.lang.Override
    public io.flourine.sdk.proto.ClientMessage getDefaultInstanceForType() {
      return io.flourine.sdk.proto.ClientMessage.getDefaultInstance();
    }

    @java.lang.Override
    public io.flourine.sdk.proto.ClientMessage build() {
      io.flourine.sdk.proto.ClientMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.flourine.sdk.proto.ClientMessage buildPartial() {
      io.flourine.sdk.proto.ClientMessage result = new io.flourine.sdk.proto.ClientMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(io.flourine.sdk.proto.ClientMessage result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(io.flourine.sdk.proto.ClientMessage result) {
      result.messageCase_ = messageCase_;
      result.message_ = this.message_;
      if (messageCase_ == 1 &&
          appendBuilder_ != null) {
        result.message_ = appendBuilder_.build();
      }
      if (messageCase_ == 2 &&
          readBuilder_ != null) {
        result.message_ = readBuilder_.build();
      }
      if (messageCase_ == 3 &&
          joinGroupBuilder_ != null) {
        result.message_ = joinGroupBuilder_.build();
      }
      if (messageCase_ == 4 &&
          heartbeatBuilder_ != null) {
        result.message_ = heartbeatBuilder_.build();
      }
      if (messageCase_ == 5 &&
          rejoinBuilder_ != null) {
        result.message_ = rejoinBuilder_.build();
      }
      if (messageCase_ == 6 &&
          leaveGroupBuilder_ != null) {
        result.message_ = leaveGroupBuilder_.build();
      }
      if (messageCase_ == 7 &&
          commitBuilder_ != null) {
        result.message_ = commitBuilder_.build();
      }
      if (messageCase_ == 8 &&
          authBuilder_ != null) {
        result.message_ = authBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.flourine.sdk.proto.ClientMessage) {
        return mergeFrom((io.flourine.sdk.proto.ClientMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.flourine.sdk.proto.ClientMessage other) {
      if (other == io.flourine.sdk.proto.ClientMessage.getDefaultInstance()) return this;
      switch (other.getMessageCase()) {
        case APPEND: {
          mergeAppend(other.getAppend());
          break;
        }
        case READ: {
          mergeRead(other.getRead());
          break;
        }
        case JOIN_GROUP: {
          mergeJoinGroup(other.getJoinGroup());
          break;
        }
        case HEARTBEAT: {
          mergeHeartbeat(other.getHeartbeat());
          break;
        }
        case REJOIN: {
          mergeRejoin(other.getRejoin());
          break;
        }
        case LEAVE_GROUP: {
          mergeLeaveGroup(other.getLeaveGroup());
          break;
        }
        case COMMIT: {
          mergeCommit(other.getCommit());
          break;
        }
        case AUTH: {
          mergeAuth(other.getAuth());
          break;
        }
        case MESSAGE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetAppendFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetReadFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetJoinGroupFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetHeartbeatFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetRejoinFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetLeaveGroupFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetCommitFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  internalGetAuthFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 8;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public MessageCase
        getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public Builder clearMessage() {
      messageCase_ = 0;
      message_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.AppendRequest, io.flourine.sdk.proto.AppendRequest.Builder, io.flourine.sdk.proto.AppendRequestOrBuilder> appendBuilder_;
    /**
     * <code>.flourine.wire.AppendRequest append = 1;</code>
     * @return Whether the append field is set.
     */
    @java.lang.Override
    public boolean hasAppend() {
      return messageCase_ == 1;
    }
    /**
     * <code>.flourine.wire.AppendRequest append = 1;</code>
     * @return The append.
     */
    @java.lang.Override
    public io.flourine.sdk.proto.AppendRequest getAppend() {
      if (appendBuilder_ == null) {
        if (messageCase_ == 1) {
          return (io.flourine.sdk.proto.AppendRequest) message_;
        }
        return io.flourine.sdk.proto.AppendRequest.getDefaultInstance();
      } else {
        if (messageCase_ == 1) {
          return appendBuilder_.getMessage();
        }
        return io.flourine.sdk.proto.AppendRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.AppendRequest append = 1;</code>
     */
    public Builder setAppend(io.flourine.sdk.proto.AppendRequest value) {
      if (appendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        appendBuilder_.setMessage(value);
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.flourine.wire.AppendRequest append = 1;</code>
     */
    public Builder setAppend(
        io.flourine.sdk.proto.AppendRequest.Builder builderForValue) {
      if (appendBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        appendBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.flourine.wire.AppendRequest append = 1;</code>
     */
    public Builder mergeAppend(io.flourine.sdk.proto.AppendRequest value) {
      if (appendBuilder_ == null) {
        if (messageCase_ == 1 &&
            message_ != io.flourine.sdk.proto.AppendRequest.getDefaultInstance()) {
          message_ = io.flourine.sdk.proto.AppendRequest.newBuilder((io.flourine.sdk.proto.AppendRequest) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 1) {
          appendBuilder_.mergeFrom(value);
        } else {
          appendBuilder_.setMessage(value);
        }
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.flourine.wire.AppendRequest append = 1;</code>
     */
    public Builder clearAppend() {
      if (appendBuilder_ == null) {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
        }
        appendBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.flourine.wire.AppendRequest append = 1;</code>
     */
    public io.flourine.sdk.proto.AppendRequest.Builder getAppendBuilder() {
      return internalGetAppendFieldBuilder().getBuilder();
    }
    /**
     * <code>.flourine.wire.AppendRequest append = 1;</code>
     */
    @java.lang.Override
    public io.flourine.sdk.proto.AppendRequestOrBuilder getAppendOrBuilder() {
      if ((messageCase_ == 1) && (appendBuilder_ != null)) {
        return appendBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 1) {
          return (io.flourine.sdk.proto.AppendRequest) message_;
        }
        return io.flourine.sdk.proto.AppendRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.AppendRequest append = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.AppendRequest, io.flourine.sdk.proto.AppendRequest.Builder, io.flourine.sdk.proto.AppendRequestOrBuilder> 
        internalGetAppendFieldBuilder() {
      if (appendBuilder_ == null) {
        if (!(messageCase_ == 1)) {
          message_ = io.flourine.sdk.proto.AppendRequest.getDefaultInstance();
        }
        appendBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.flourine.sdk.proto.AppendRequest, io.flourine.sdk.proto.AppendRequest.Builder, io.flourine.sdk.proto.AppendRequestOrBuilder>(
                (io.flourine.sdk.proto.AppendRequest) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 1;
      onChanged();
      return appendBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.ReadRequest, io.flourine.sdk.proto.ReadRequest.Builder, io.flourine.sdk.proto.ReadRequestOrBuilder> readBuilder_;
    /**
     * <code>.flourine.wire.ReadRequest read = 2;</code>
     * @return Whether the read field is set.
     */
    @java.lang.Override
    public boolean hasRead() {
      return messageCase_ == 2;
    }
    /**
     * <code>.flourine.wire.ReadRequest read = 2;</code>
     * @return The read.
     */
    @java.lang.Override
    public io.flourine.sdk.proto.ReadRequest getRead() {
      if (readBuilder_ == null) {
        if (messageCase_ == 2) {
          return (io.flourine.sdk.proto.ReadRequest) message_;
        }
        return io.flourine.sdk.proto.ReadRequest.getDefaultInstance();
      } else {
        if (messageCase_ == 2) {
          return readBuilder_.getMessage();
        }
        return io.flourine.sdk.proto.ReadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.ReadRequest read = 2;</code>
     */
    public Builder setRead(io.flourine.sdk.proto.ReadRequest value) {
      if (readBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        readBuilder_.setMessage(value);
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.flourine.wire.ReadRequest read = 2;</code>
     */
    public Builder setRead(
        io.flourine.sdk.proto.ReadRequest.Builder builderForValue) {
      if (readBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        readBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.flourine.wire.ReadRequest read = 2;</code>
     */
    public Builder mergeRead(io.flourine.sdk.proto.ReadRequest value) {
      if (readBuilder_ == null) {
        if (messageCase_ == 2 &&
            message_ != io.flourine.sdk.proto.ReadRequest.getDefaultInstance()) {
          message_ = io.flourine.sdk.proto.ReadRequest.newBuilder((io.flourine.sdk.proto.ReadRequest) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 2) {
          readBuilder_.mergeFrom(value);
        } else {
          readBuilder_.setMessage(value);
        }
      }
      messageCase_ = 2;
      return this;
    }
    /**
     * <code>.flourine.wire.ReadRequest read = 2;</code>
     */
    public Builder clearRead() {
      if (readBuilder_ == null) {
        if (messageCase_ == 2) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 2) {
          messageCase_ = 0;
          message_ = null;
        }
        readBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.flourine.wire.ReadRequest read = 2;</code>
     */
    public io.flourine.sdk.proto.ReadRequest.Builder getReadBuilder() {
      return internalGetReadFieldBuilder().getBuilder();
    }
    /**
     * <code>.flourine.wire.ReadRequest read = 2;</code>
     */
    @java.lang.Override
    public io.flourine.sdk.proto.ReadRequestOrBuilder getReadOrBuilder() {
      if ((messageCase_ == 2) && (readBuilder_ != null)) {
        return readBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 2) {
          return (io.flourine.sdk.proto.ReadRequest) message_;
        }
        return io.flourine.sdk.proto.ReadRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.ReadRequest read = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.ReadRequest, io.flourine.sdk.proto.ReadRequest.Builder, io.flourine.sdk.proto.ReadRequestOrBuilder> 
        internalGetReadFieldBuilder() {
      if (readBuilder_ == null) {
        if (!(messageCase_ == 2)) {
          message_ = io.flourine.sdk.proto.ReadRequest.getDefaultInstance();
        }
        readBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.flourine.sdk.proto.ReadRequest, io.flourine.sdk.proto.ReadRequest.Builder, io.flourine.sdk.proto.ReadRequestOrBuilder>(
                (io.flourine.sdk.proto.ReadRequest) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 2;
      onChanged();
      return readBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.JoinGroupRequest, io.flourine.sdk.proto.JoinGroupRequest.Builder, io.flourine.sdk.proto.JoinGroupRequestOrBuilder> joinGroupBuilder_;
    /**
     * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
     * @return Whether the joinGroup field is set.
     */
    @java.lang.Override
    public boolean hasJoinGroup() {
      return messageCase_ == 3;
    }
    /**
     * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
     * @return The joinGroup.
     */
    @java.lang.Override
    public io.flourine.sdk.proto.JoinGroupRequest getJoinGroup() {
      if (joinGroupBuilder_ == null) {
        if (messageCase_ == 3) {
          return (io.flourine.sdk.proto.JoinGroupRequest) message_;
        }
        return io.flourine.sdk.proto.JoinGroupRequest.getDefaultInstance();
      } else {
        if (messageCase_ == 3) {
          return joinGroupBuilder_.getMessage();
        }
        return io.flourine.sdk.proto.JoinGroupRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
     */
    public Builder setJoinGroup(io.flourine.sdk.proto.JoinGroupRequest value) {
      if (joinGroupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        joinGroupBuilder_.setMessage(value);
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
     */
    public Builder setJoinGroup(
        io.flourine.sdk.proto.JoinGroupRequest.Builder builderForValue) {
      if (joinGroupBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        joinGroupBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
     */
    public Builder mergeJoinGroup(io.flourine.sdk.proto.JoinGroupRequest value) {
      if (joinGroupBuilder_ == null) {
        if (messageCase_ == 3 &&
            message_ != io.flourine.sdk.proto.JoinGroupRequest.getDefaultInstance()) {
          message_ = io.flourine.sdk.proto.JoinGroupRequest.newBuilder((io.flourine.sdk.proto.JoinGroupRequest) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 3) {
          joinGroupBuilder_.mergeFrom(value);
        } else {
          joinGroupBuilder_.setMessage(value);
        }
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
     */
    public Builder clearJoinGroup() {
      if (joinGroupBuilder_ == null) {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
        }
        joinGroupBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
     */
    public io.flourine.sdk.proto.JoinGroupRequest.Builder getJoinGroupBuilder() {
      return internalGetJoinGroupFieldBuilder().getBuilder();
    }
    /**
     * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
     */
    @java.lang.Override
    public io.flourine.sdk.proto.JoinGroupRequestOrBuilder getJoinGroupOrBuilder() {
      if ((messageCase_ == 3) && (joinGroupBuilder_ != null)) {
        return joinGroupBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 3) {
          return (io.flourine.sdk.proto.JoinGroupRequest) message_;
        }
        return io.flourine.sdk.proto.JoinGroupRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.JoinGroupRequest join_group = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.JoinGroupRequest, io.flourine.sdk.proto.JoinGroupRequest.Builder, io.flourine.sdk.proto.JoinGroupRequestOrBuilder> 
        internalGetJoinGroupFieldBuilder() {
      if (joinGroupBuilder_ == null) {
        if (!(messageCase_ == 3)) {
          message_ = io.flourine.sdk.proto.JoinGroupRequest.getDefaultInstance();
        }
        joinGroupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.flourine.sdk.proto.JoinGroupRequest, io.flourine.sdk.proto.JoinGroupRequest.Builder, io.flourine.sdk.proto.JoinGroupRequestOrBuilder>(
                (io.flourine.sdk.proto.JoinGroupRequest) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 3;
      onChanged();
      return joinGroupBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.HeartbeatRequest, io.flourine.sdk.proto.HeartbeatRequest.Builder, io.flourine.sdk.proto.HeartbeatRequestOrBuilder> heartbeatBuilder_;
    /**
     * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
     * @return Whether the heartbeat field is set.
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return messageCase_ == 4;
    }
    /**
     * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
     * @return The heartbeat.
     */
    @java.lang.Override
    public io.flourine.sdk.proto.HeartbeatRequest getHeartbeat() {
      if (heartbeatBuilder_ == null) {
        if (messageCase_ == 4) {
          return (io.flourine.sdk.proto.HeartbeatRequest) message_;
        }
        return io.flourine.sdk.proto.HeartbeatRequest.getDefaultInstance();
      } else {
        if (messageCase_ == 4) {
          return heartbeatBuilder_.getMessage();
        }
        return io.flourine.sdk.proto.HeartbeatRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
     */
    public Builder setHeartbeat(io.flourine.sdk.proto.HeartbeatRequest value) {
      if (heartbeatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(value);
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
     */
    public Builder setHeartbeat(
        io.flourine.sdk.proto.HeartbeatRequest.Builder builderForValue) {
      if (heartbeatBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
     */
    public Builder mergeHeartbeat(io.flourine.sdk.proto.HeartbeatRequest value) {
      if (heartbeatBuilder_ == null) {
        if (messageCase_ == 4 &&
            message_ != io.flourine.sdk.proto.HeartbeatRequest.getDefaultInstance()) {
          message_ = io.flourine.sdk.proto.HeartbeatRequest.newBuilder((io.flourine.sdk.proto.HeartbeatRequest) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 4) {
          heartbeatBuilder_.mergeFrom(value);
        } else {
          heartbeatBuilder_.setMessage(value);
        }
      }
      messageCase_ = 4;
      return this;
    }
    /**
     * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
     */
    public Builder clearHeartbeat() {
      if (heartbeatBuilder_ == null) {
        if (messageCase_ == 4) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 4) {
          messageCase_ = 0;
          message_ = null;
        }
        heartbeatBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
     */
    public io.flourine.sdk.proto.HeartbeatRequest.Builder getHeartbeatBuilder() {
      return internalGetHeartbeatFieldBuilder().getBuilder();
    }
    /**
     * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
     */
    @java.lang.Override
    public io.flourine.sdk.proto.HeartbeatRequestOrBuilder getHeartbeatOrBuilder() {
      if ((messageCase_ == 4) && (heartbeatBuilder_ != null)) {
        return heartbeatBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 4) {
          return (io.flourine.sdk.proto.HeartbeatRequest) message_;
        }
        return io.flourine.sdk.proto.HeartbeatRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.HeartbeatRequest heartbeat = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.HeartbeatRequest, io.flourine.sdk.proto.HeartbeatRequest.Builder, io.flourine.sdk.proto.HeartbeatRequestOrBuilder> 
        internalGetHeartbeatFieldBuilder() {
      if (heartbeatBuilder_ == null) {
        if (!(messageCase_ == 4)) {
          message_ = io.flourine.sdk.proto.HeartbeatRequest.getDefaultInstance();
        }
        heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.flourine.sdk.proto.HeartbeatRequest, io.flourine.sdk.proto.HeartbeatRequest.Builder, io.flourine.sdk.proto.HeartbeatRequestOrBuilder>(
                (io.flourine.sdk.proto.HeartbeatRequest) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 4;
      onChanged();
      return heartbeatBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.RejoinRequest, io.flourine.sdk.proto.RejoinRequest.Builder, io.flourine.sdk.proto.RejoinRequestOrBuilder> rejoinBuilder_;
    /**
     * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
     * @return Whether the rejoin field is set.
     */
    @java.lang.Override
    public boolean hasRejoin() {
      return messageCase_ == 5;
    }
    /**
     * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
     * @return The rejoin.
     */
    @java.lang.Override
    public io.flourine.sdk.proto.RejoinRequest getRejoin() {
      if (rejoinBuilder_ == null) {
        if (messageCase_ == 5) {
          return (io.flourine.sdk.proto.RejoinRequest) message_;
        }
        return io.flourine.sdk.proto.RejoinRequest.getDefaultInstance();
      } else {
        if (messageCase_ == 5) {
          return rejoinBuilder_.getMessage();
        }
        return io.flourine.sdk.proto.RejoinRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
     */
    public Builder setRejoin(io.flourine.sdk.proto.RejoinRequest value) {
      if (rejoinBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        rejoinBuilder_.setMessage(value);
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
     */
    public Builder setRejoin(
        io.flourine.sdk.proto.RejoinRequest.Builder builderForValue) {
      if (rejoinBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        rejoinBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
     */
    public Builder mergeRejoin(io.flourine.sdk.proto.RejoinRequest value) {
      if (rejoinBuilder_ == null) {
        if (messageCase_ == 5 &&
            message_ != io.flourine.sdk.proto.RejoinRequest.getDefaultInstance()) {
          message_ = io.flourine.sdk.proto.RejoinRequest.newBuilder((io.flourine.sdk.proto.RejoinRequest) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 5) {
          rejoinBuilder_.mergeFrom(value);
        } else {
          rejoinBuilder_.setMessage(value);
        }
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
     */
    public Builder clearRejoin() {
      if (rejoinBuilder_ == null) {
        if (messageCase_ == 5) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 5) {
          messageCase_ = 0;
          message_ = null;
        }
        rejoinBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
     */
    public io.flourine.sdk.proto.RejoinRequest.Builder getRejoinBuilder() {
      return internalGetRejoinFieldBuilder().getBuilder();
    }
    /**
     * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
     */
    @java.lang.Override
    public io.flourine.sdk.proto.RejoinRequestOrBuilder getRejoinOrBuilder() {
      if ((messageCase_ == 5) && (rejoinBuilder_ != null)) {
        return rejoinBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 5) {
          return (io.flourine.sdk.proto.RejoinRequest) message_;
        }
        return io.flourine.sdk.proto.RejoinRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.RejoinRequest rejoin = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.RejoinRequest, io.flourine.sdk.proto.RejoinRequest.Builder, io.flourine.sdk.proto.RejoinRequestOrBuilder> 
        internalGetRejoinFieldBuilder() {
      if (rejoinBuilder_ == null) {
        if (!(messageCase_ == 5)) {
          message_ = io.flourine.sdk.proto.RejoinRequest.getDefaultInstance();
        }
        rejoinBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.flourine.sdk.proto.RejoinRequest, io.flourine.sdk.proto.RejoinRequest.Builder, io.flourine.sdk.proto.RejoinRequestOrBuilder>(
                (io.flourine.sdk.proto.RejoinRequest) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 5;
      onChanged();
      return rejoinBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.LeaveGroupRequest, io.flourine.sdk.proto.LeaveGroupRequest.Builder, io.flourine.sdk.proto.LeaveGroupRequestOrBuilder> leaveGroupBuilder_;
    /**
     * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
     * @return Whether the leaveGroup field is set.
     */
    @java.lang.Override
    public boolean hasLeaveGroup() {
      return messageCase_ == 6;
    }
    /**
     * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
     * @return The leaveGroup.
     */
    @java.lang.Override
    public io.flourine.sdk.proto.LeaveGroupRequest getLeaveGroup() {
      if (leaveGroupBuilder_ == null) {
        if (messageCase_ == 6) {
          return (io.flourine.sdk.proto.LeaveGroupRequest) message_;
        }
        return io.flourine.sdk.proto.LeaveGroupRequest.getDefaultInstance();
      } else {
        if (messageCase_ == 6) {
          return leaveGroupBuilder_.getMessage();
        }
        return io.flourine.sdk.proto.LeaveGroupRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
     */
    public Builder setLeaveGroup(io.flourine.sdk.proto.LeaveGroupRequest value) {
      if (leaveGroupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        leaveGroupBuilder_.setMessage(value);
      }
      messageCase_ = 6;
      return this;
    }
    /**
     * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
     */
    public Builder setLeaveGroup(
        io.flourine.sdk.proto.LeaveGroupRequest.Builder builderForValue) {
      if (leaveGroupBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        leaveGroupBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 6;
      return this;
    }
    /**
     * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
     */
    public Builder mergeLeaveGroup(io.flourine.sdk.proto.LeaveGroupRequest value) {
      if (leaveGroupBuilder_ == null) {
        if (messageCase_ == 6 &&
            message_ != io.flourine.sdk.proto.LeaveGroupRequest.getDefaultInstance()) {
          message_ = io.flourine.sdk.proto.LeaveGroupRequest.newBuilder((io.flourine.sdk.proto.LeaveGroupRequest) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 6) {
          leaveGroupBuilder_.mergeFrom(value);
        } else {
          leaveGroupBuilder_.setMessage(value);
        }
      }
      messageCase_ = 6;
      return this;
    }
    /**
     * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
     */
    public Builder clearLeaveGroup() {
      if (leaveGroupBuilder_ == null) {
        if (messageCase_ == 6) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 6) {
          messageCase_ = 0;
          message_ = null;
        }
        leaveGroupBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
     */
    public io.flourine.sdk.proto.LeaveGroupRequest.Builder getLeaveGroupBuilder() {
      return internalGetLeaveGroupFieldBuilder().getBuilder();
    }
    /**
     * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
     */
    @java.lang.Override
    public io.flourine.sdk.proto.LeaveGroupRequestOrBuilder getLeaveGroupOrBuilder() {
      if ((messageCase_ == 6) && (leaveGroupBuilder_ != null)) {
        return leaveGroupBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 6) {
          return (io.flourine.sdk.proto.LeaveGroupRequest) message_;
        }
        return io.flourine.sdk.proto.LeaveGroupRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.LeaveGroupRequest leave_group = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.LeaveGroupRequest, io.flourine.sdk.proto.LeaveGroupRequest.Builder, io.flourine.sdk.proto.LeaveGroupRequestOrBuilder> 
        internalGetLeaveGroupFieldBuilder() {
      if (leaveGroupBuilder_ == null) {
        if (!(messageCase_ == 6)) {
          message_ = io.flourine.sdk.proto.LeaveGroupRequest.getDefaultInstance();
        }
        leaveGroupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.flourine.sdk.proto.LeaveGroupRequest, io.flourine.sdk.proto.LeaveGroupRequest.Builder, io.flourine.sdk.proto.LeaveGroupRequestOrBuilder>(
                (io.flourine.sdk.proto.LeaveGroupRequest) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 6;
      onChanged();
      return leaveGroupBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.CommitRequest, io.flourine.sdk.proto.CommitRequest.Builder, io.flourine.sdk.proto.CommitRequestOrBuilder> commitBuilder_;
    /**
     * <code>.flourine.wire.CommitRequest commit = 7;</code>
     * @return Whether the commit field is set.
     */
    @java.lang.Override
    public boolean hasCommit() {
      return messageCase_ == 7;
    }
    /**
     * <code>.flourine.wire.CommitRequest commit = 7;</code>
     * @return The commit.
     */
    @java.lang.Override
    public io.flourine.sdk.proto.CommitRequest getCommit() {
      if (commitBuilder_ == null) {
        if (messageCase_ == 7) {
          return (io.flourine.sdk.proto.CommitRequest) message_;
        }
        return io.flourine.sdk.proto.CommitRequest.getDefaultInstance();
      } else {
        if (messageCase_ == 7) {
          return commitBuilder_.getMessage();
        }
        return io.flourine.sdk.proto.CommitRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.CommitRequest commit = 7;</code>
     */
    public Builder setCommit(io.flourine.sdk.proto.CommitRequest value) {
      if (commitBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        commitBuilder_.setMessage(value);
      }
      messageCase_ = 7;
      return this;
    }
    /**
     * <code>.flourine.wire.CommitRequest commit = 7;</code>
     */
    public Builder setCommit(
        io.flourine.sdk.proto.CommitRequest.Builder builderForValue) {
      if (commitBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        commitBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 7;
      return this;
    }
    /**
     * <code>.flourine.wire.CommitRequest commit = 7;</code>
     */
    public Builder mergeCommit(io.flourine.sdk.proto.CommitRequest value) {
      if (commitBuilder_ == null) {
        if (messageCase_ == 7 &&
            message_ != io.flourine.sdk.proto.CommitRequest.getDefaultInstance()) {
          message_ = io.flourine.sdk.proto.CommitRequest.newBuilder((io.flourine.sdk.proto.CommitRequest) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 7) {
          commitBuilder_.mergeFrom(value);
        } else {
          commitBuilder_.setMessage(value);
        }
      }
      messageCase_ = 7;
      return this;
    }
    /**
     * <code>.flourine.wire.CommitRequest commit = 7;</code>
     */
    public Builder clearCommit() {
      if (commitBuilder_ == null) {
        if (messageCase_ == 7) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 7) {
          messageCase_ = 0;
          message_ = null;
        }
        commitBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.flourine.wire.CommitRequest commit = 7;</code>
     */
    public io.flourine.sdk.proto.CommitRequest.Builder getCommitBuilder() {
      return internalGetCommitFieldBuilder().getBuilder();
    }
    /**
     * <code>.flourine.wire.CommitRequest commit = 7;</code>
     */
    @java.lang.Override
    public io.flourine.sdk.proto.CommitRequestOrBuilder getCommitOrBuilder() {
      if ((messageCase_ == 7) && (commitBuilder_ != null)) {
        return commitBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 7) {
          return (io.flourine.sdk.proto.CommitRequest) message_;
        }
        return io.flourine.sdk.proto.CommitRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.CommitRequest commit = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.CommitRequest, io.flourine.sdk.proto.CommitRequest.Builder, io.flourine.sdk.proto.CommitRequestOrBuilder> 
        internalGetCommitFieldBuilder() {
      if (commitBuilder_ == null) {
        if (!(messageCase_ == 7)) {
          message_ = io.flourine.sdk.proto.CommitRequest.getDefaultInstance();
        }
        commitBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.flourine.sdk.proto.CommitRequest, io.flourine.sdk.proto.CommitRequest.Builder, io.flourine.sdk.proto.CommitRequestOrBuilder>(
                (io.flourine.sdk.proto.CommitRequest) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 7;
      onChanged();
      return commitBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.AuthRequest, io.flourine.sdk.proto.AuthRequest.Builder, io.flourine.sdk.proto.AuthRequestOrBuilder> authBuilder_;
    /**
     * <code>.flourine.wire.AuthRequest auth = 8;</code>
     * @return Whether the auth field is set.
     */
    @java.lang.Override
    public boolean hasAuth() {
      return messageCase_ == 8;
    }
    /**
     * <code>.flourine.wire.AuthRequest auth = 8;</code>
     * @return The auth.
     */
    @java.lang.Override
    public io.flourine.sdk.proto.AuthRequest getAuth() {
      if (authBuilder_ == null) {
        if (messageCase_ == 8) {
          return (io.flourine.sdk.proto.AuthRequest) message_;
        }
        return io.flourine.sdk.proto.AuthRequest.getDefaultInstance();
      } else {
        if (messageCase_ == 8) {
          return authBuilder_.getMessage();
        }
        return io.flourine.sdk.proto.AuthRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.AuthRequest auth = 8;</code>
     */
    public Builder setAuth(io.flourine.sdk.proto.AuthRequest value) {
      if (authBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        authBuilder_.setMessage(value);
      }
      messageCase_ = 8;
      return this;
    }
    /**
     * <code>.flourine.wire.AuthRequest auth = 8;</code>
     */
    public Builder setAuth(
        io.flourine.sdk.proto.AuthRequest.Builder builderForValue) {
      if (authBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        authBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 8;
      return this;
    }
    /**
     * <code>.flourine.wire.AuthRequest auth = 8;</code>
     */
    public Builder mergeAuth(io.flourine.sdk.proto.AuthRequest value) {
      if (authBuilder_ == null) {
        if (messageCase_ == 8 &&
            message_ != io.flourine.sdk.proto.AuthRequest.getDefaultInstance()) {
          message_ = io.flourine.sdk.proto.AuthRequest.newBuilder((io.flourine.sdk.proto.AuthRequest) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 8) {
          authBuilder_.mergeFrom(value);
        } else {
          authBuilder_.setMessage(value);
        }
      }
      messageCase_ = 8;
      return this;
    }
    /**
     * <code>.flourine.wire.AuthRequest auth = 8;</code>
     */
    public Builder clearAuth() {
      if (authBuilder_ == null) {
        if (messageCase_ == 8) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 8) {
          messageCase_ = 0;
          message_ = null;
        }
        authBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.flourine.wire.AuthRequest auth = 8;</code>
     */
    public io.flourine.sdk.proto.AuthRequest.Builder getAuthBuilder() {
      return internalGetAuthFieldBuilder().getBuilder();
    }
    /**
     * <code>.flourine.wire.AuthRequest auth = 8;</code>
     */
    @java.lang.Override
    public io.flourine.sdk.proto.AuthRequestOrBuilder getAuthOrBuilder() {
      if ((messageCase_ == 8) && (authBuilder_ != null)) {
        return authBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 8) {
          return (io.flourine.sdk.proto.AuthRequest) message_;
        }
        return io.flourine.sdk.proto.AuthRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.flourine.wire.AuthRequest auth = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.flourine.sdk.proto.AuthRequest, io.flourine.sdk.proto.AuthRequest.Builder, io.flourine.sdk.proto.AuthRequestOrBuilder> 
        internalGetAuthFieldBuilder() {
      if (authBuilder_ == null) {
        if (!(messageCase_ == 8)) {
          message_ = io.flourine.sdk.proto.AuthRequest.getDefaultInstance();
        }
        authBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.flourine.sdk.proto.AuthRequest, io.flourine.sdk.proto.AuthRequest.Builder, io.flourine.sdk.proto.AuthRequestOrBuilder>(
                (io.flourine.sdk.proto.AuthRequest) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 8;
      onChanged();
      return authBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:flourine.wire.ClientMessage)
  }

  // @@protoc_insertion_point(class_scope:flourine.wire.ClientMessage)
  private static final io.flourine.sdk.proto.ClientMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.flourine.sdk.proto.ClientMessage();
  }

  public static io.flourine.sdk.proto.ClientMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientMessage>
      PARSER = new com.google.protobuf.AbstractParser<ClientMessage>() {
    @java.lang.Override
    public ClientMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClientMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.flourine.sdk.proto.ClientMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

