// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flourine_wire.proto
// Protobuf Java Version: 4.33.4

package io.flourine.sdk.proto;

/**
 * Protobuf type {@code flourine.wire.CommitRequest}
 */
@com.google.protobuf.Generated
public final class CommitRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flourine.wire.CommitRequest)
    CommitRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "CommitRequest");
  }
  // Use CommitRequest.newBuilder() to construct.
  private CommitRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CommitRequest() {
    groupId_ = "";
    readerId_ = "";
    commits_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_CommitRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_CommitRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.flourine.sdk.proto.CommitRequest.class, io.flourine.sdk.proto.CommitRequest.Builder.class);
  }

  public static final int GROUP_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object groupId_ = "";
  /**
   * <code>string group_id = 1;</code>
   * @return The groupId.
   */
  @java.lang.Override
  public java.lang.String getGroupId() {
    java.lang.Object ref = groupId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupId_ = s;
      return s;
    }
  }
  /**
   * <code>string group_id = 1;</code>
   * @return The bytes for groupId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupIdBytes() {
    java.lang.Object ref = groupId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int READER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object readerId_ = "";
  /**
   * <code>string reader_id = 2;</code>
   * @return The readerId.
   */
  @java.lang.Override
  public java.lang.String getReaderId() {
    java.lang.Object ref = readerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      readerId_ = s;
      return s;
    }
  }
  /**
   * <code>string reader_id = 2;</code>
   * @return The bytes for readerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReaderIdBytes() {
    java.lang.Object ref = readerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      readerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENERATION_FIELD_NUMBER = 3;
  private long generation_ = 0L;
  /**
   * <code>uint64 generation = 3;</code>
   * @return The generation.
   */
  @java.lang.Override
  public long getGeneration() {
    return generation_;
  }

  public static final int COMMITS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<io.flourine.sdk.proto.PartitionCommit> commits_;
  /**
   * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
   */
  @java.lang.Override
  public java.util.List<io.flourine.sdk.proto.PartitionCommit> getCommitsList() {
    return commits_;
  }
  /**
   * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.flourine.sdk.proto.PartitionCommitOrBuilder> 
      getCommitsOrBuilderList() {
    return commits_;
  }
  /**
   * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
   */
  @java.lang.Override
  public int getCommitsCount() {
    return commits_.size();
  }
  /**
   * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.PartitionCommit getCommits(int index) {
    return commits_.get(index);
  }
  /**
   * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.PartitionCommitOrBuilder getCommitsOrBuilder(
      int index) {
    return commits_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, groupId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(readerId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, readerId_);
    }
    if (generation_ != 0L) {
      output.writeUInt64(3, generation_);
    }
    for (int i = 0; i < commits_.size(); i++) {
      output.writeMessage(4, commits_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, groupId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(readerId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, readerId_);
    }
    if (generation_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, generation_);
    }
    for (int i = 0; i < commits_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, commits_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.flourine.sdk.proto.CommitRequest)) {
      return super.equals(obj);
    }
    io.flourine.sdk.proto.CommitRequest other = (io.flourine.sdk.proto.CommitRequest) obj;

    if (!getGroupId()
        .equals(other.getGroupId())) return false;
    if (!getReaderId()
        .equals(other.getReaderId())) return false;
    if (getGeneration()
        != other.getGeneration()) return false;
    if (!getCommitsList()
        .equals(other.getCommitsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGroupId().hashCode();
    hash = (37 * hash) + READER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReaderId().hashCode();
    hash = (37 * hash) + GENERATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGeneration());
    if (getCommitsCount() > 0) {
      hash = (37 * hash) + COMMITS_FIELD_NUMBER;
      hash = (53 * hash) + getCommitsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.flourine.sdk.proto.CommitRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.CommitRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.CommitRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.CommitRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.CommitRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.CommitRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.CommitRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flourine.sdk.proto.CommitRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.flourine.sdk.proto.CommitRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.flourine.sdk.proto.CommitRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.flourine.sdk.proto.CommitRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flourine.sdk.proto.CommitRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.flourine.sdk.proto.CommitRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code flourine.wire.CommitRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flourine.wire.CommitRequest)
      io.flourine.sdk.proto.CommitRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_CommitRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_CommitRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.flourine.sdk.proto.CommitRequest.class, io.flourine.sdk.proto.CommitRequest.Builder.class);
    }

    // Construct using io.flourine.sdk.proto.CommitRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      groupId_ = "";
      readerId_ = "";
      generation_ = 0L;
      if (commitsBuilder_ == null) {
        commits_ = java.util.Collections.emptyList();
      } else {
        commits_ = null;
        commitsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_CommitRequest_descriptor;
    }

    @java.lang.Override
    public io.flourine.sdk.proto.CommitRequest getDefaultInstanceForType() {
      return io.flourine.sdk.proto.CommitRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.flourine.sdk.proto.CommitRequest build() {
      io.flourine.sdk.proto.CommitRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.flourine.sdk.proto.CommitRequest buildPartial() {
      io.flourine.sdk.proto.CommitRequest result = new io.flourine.sdk.proto.CommitRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.flourine.sdk.proto.CommitRequest result) {
      if (commitsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          commits_ = java.util.Collections.unmodifiableList(commits_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.commits_ = commits_;
      } else {
        result.commits_ = commitsBuilder_.build();
      }
    }

    private void buildPartial0(io.flourine.sdk.proto.CommitRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.groupId_ = groupId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.readerId_ = readerId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.generation_ = generation_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.flourine.sdk.proto.CommitRequest) {
        return mergeFrom((io.flourine.sdk.proto.CommitRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.flourine.sdk.proto.CommitRequest other) {
      if (other == io.flourine.sdk.proto.CommitRequest.getDefaultInstance()) return this;
      if (!other.getGroupId().isEmpty()) {
        groupId_ = other.groupId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getReaderId().isEmpty()) {
        readerId_ = other.readerId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getGeneration() != 0L) {
        setGeneration(other.getGeneration());
      }
      if (commitsBuilder_ == null) {
        if (!other.commits_.isEmpty()) {
          if (commits_.isEmpty()) {
            commits_ = other.commits_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCommitsIsMutable();
            commits_.addAll(other.commits_);
          }
          onChanged();
        }
      } else {
        if (!other.commits_.isEmpty()) {
          if (commitsBuilder_.isEmpty()) {
            commitsBuilder_.dispose();
            commitsBuilder_ = null;
            commits_ = other.commits_;
            bitField0_ = (bitField0_ & ~0x00000008);
            commitsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetCommitsFieldBuilder() : null;
          } else {
            commitsBuilder_.addAllMessages(other.commits_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              groupId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              readerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              generation_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              io.flourine.sdk.proto.PartitionCommit m =
                  input.readMessage(
                      io.flourine.sdk.proto.PartitionCommit.parser(),
                      extensionRegistry);
              if (commitsBuilder_ == null) {
                ensureCommitsIsMutable();
                commits_.add(m);
              } else {
                commitsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object groupId_ = "";
    /**
     * <code>string group_id = 1;</code>
     * @return The groupId.
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string group_id = 1;</code>
     * @return The bytes for groupId.
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string group_id = 1;</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      groupId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string group_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      groupId_ = getDefaultInstance().getGroupId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string group_id = 1;</code>
     * @param value The bytes for groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      groupId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object readerId_ = "";
    /**
     * <code>string reader_id = 2;</code>
     * @return The readerId.
     */
    public java.lang.String getReaderId() {
      java.lang.Object ref = readerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reader_id = 2;</code>
     * @return The bytes for readerId.
     */
    public com.google.protobuf.ByteString
        getReaderIdBytes() {
      java.lang.Object ref = readerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reader_id = 2;</code>
     * @param value The readerId to set.
     * @return This builder for chaining.
     */
    public Builder setReaderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      readerId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string reader_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReaderId() {
      readerId_ = getDefaultInstance().getReaderId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string reader_id = 2;</code>
     * @param value The bytes for readerId to set.
     * @return This builder for chaining.
     */
    public Builder setReaderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      readerId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long generation_ ;
    /**
     * <code>uint64 generation = 3;</code>
     * @return The generation.
     */
    @java.lang.Override
    public long getGeneration() {
      return generation_;
    }
    /**
     * <code>uint64 generation = 3;</code>
     * @param value The generation to set.
     * @return This builder for chaining.
     */
    public Builder setGeneration(long value) {

      generation_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 generation = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGeneration() {
      bitField0_ = (bitField0_ & ~0x00000004);
      generation_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<io.flourine.sdk.proto.PartitionCommit> commits_ =
      java.util.Collections.emptyList();
    private void ensureCommitsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        commits_ = new java.util.ArrayList<io.flourine.sdk.proto.PartitionCommit>(commits_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.flourine.sdk.proto.PartitionCommit, io.flourine.sdk.proto.PartitionCommit.Builder, io.flourine.sdk.proto.PartitionCommitOrBuilder> commitsBuilder_;

    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public java.util.List<io.flourine.sdk.proto.PartitionCommit> getCommitsList() {
      if (commitsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(commits_);
      } else {
        return commitsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public int getCommitsCount() {
      if (commitsBuilder_ == null) {
        return commits_.size();
      } else {
        return commitsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public io.flourine.sdk.proto.PartitionCommit getCommits(int index) {
      if (commitsBuilder_ == null) {
        return commits_.get(index);
      } else {
        return commitsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public Builder setCommits(
        int index, io.flourine.sdk.proto.PartitionCommit value) {
      if (commitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommitsIsMutable();
        commits_.set(index, value);
        onChanged();
      } else {
        commitsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public Builder setCommits(
        int index, io.flourine.sdk.proto.PartitionCommit.Builder builderForValue) {
      if (commitsBuilder_ == null) {
        ensureCommitsIsMutable();
        commits_.set(index, builderForValue.build());
        onChanged();
      } else {
        commitsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public Builder addCommits(io.flourine.sdk.proto.PartitionCommit value) {
      if (commitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommitsIsMutable();
        commits_.add(value);
        onChanged();
      } else {
        commitsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public Builder addCommits(
        int index, io.flourine.sdk.proto.PartitionCommit value) {
      if (commitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommitsIsMutable();
        commits_.add(index, value);
        onChanged();
      } else {
        commitsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public Builder addCommits(
        io.flourine.sdk.proto.PartitionCommit.Builder builderForValue) {
      if (commitsBuilder_ == null) {
        ensureCommitsIsMutable();
        commits_.add(builderForValue.build());
        onChanged();
      } else {
        commitsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public Builder addCommits(
        int index, io.flourine.sdk.proto.PartitionCommit.Builder builderForValue) {
      if (commitsBuilder_ == null) {
        ensureCommitsIsMutable();
        commits_.add(index, builderForValue.build());
        onChanged();
      } else {
        commitsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public Builder addAllCommits(
        java.lang.Iterable<? extends io.flourine.sdk.proto.PartitionCommit> values) {
      if (commitsBuilder_ == null) {
        ensureCommitsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, commits_);
        onChanged();
      } else {
        commitsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public Builder clearCommits() {
      if (commitsBuilder_ == null) {
        commits_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        commitsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public Builder removeCommits(int index) {
      if (commitsBuilder_ == null) {
        ensureCommitsIsMutable();
        commits_.remove(index);
        onChanged();
      } else {
        commitsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public io.flourine.sdk.proto.PartitionCommit.Builder getCommitsBuilder(
        int index) {
      return internalGetCommitsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public io.flourine.sdk.proto.PartitionCommitOrBuilder getCommitsOrBuilder(
        int index) {
      if (commitsBuilder_ == null) {
        return commits_.get(index);  } else {
        return commitsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public java.util.List<? extends io.flourine.sdk.proto.PartitionCommitOrBuilder> 
         getCommitsOrBuilderList() {
      if (commitsBuilder_ != null) {
        return commitsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(commits_);
      }
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public io.flourine.sdk.proto.PartitionCommit.Builder addCommitsBuilder() {
      return internalGetCommitsFieldBuilder().addBuilder(
          io.flourine.sdk.proto.PartitionCommit.getDefaultInstance());
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public io.flourine.sdk.proto.PartitionCommit.Builder addCommitsBuilder(
        int index) {
      return internalGetCommitsFieldBuilder().addBuilder(
          index, io.flourine.sdk.proto.PartitionCommit.getDefaultInstance());
    }
    /**
     * <code>repeated .flourine.wire.PartitionCommit commits = 4;</code>
     */
    public java.util.List<io.flourine.sdk.proto.PartitionCommit.Builder> 
         getCommitsBuilderList() {
      return internalGetCommitsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.flourine.sdk.proto.PartitionCommit, io.flourine.sdk.proto.PartitionCommit.Builder, io.flourine.sdk.proto.PartitionCommitOrBuilder> 
        internalGetCommitsFieldBuilder() {
      if (commitsBuilder_ == null) {
        commitsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.flourine.sdk.proto.PartitionCommit, io.flourine.sdk.proto.PartitionCommit.Builder, io.flourine.sdk.proto.PartitionCommitOrBuilder>(
                commits_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        commits_ = null;
      }
      return commitsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:flourine.wire.CommitRequest)
  }

  // @@protoc_insertion_point(class_scope:flourine.wire.CommitRequest)
  private static final io.flourine.sdk.proto.CommitRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.flourine.sdk.proto.CommitRequest();
  }

  public static io.flourine.sdk.proto.CommitRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommitRequest>
      PARSER = new com.google.protobuf.AbstractParser<CommitRequest>() {
    @java.lang.Override
    public CommitRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CommitRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommitRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.flourine.sdk.proto.CommitRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

