// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flourine_wire.proto
// Protobuf Java Version: 4.33.4

package io.flourine.sdk.proto;

/**
 * Protobuf type {@code flourine.wire.HeartbeatRequest}
 */
@com.google.protobuf.Generated
public final class HeartbeatRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flourine.wire.HeartbeatRequest)
    HeartbeatRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "HeartbeatRequest");
  }
  // Use HeartbeatRequest.newBuilder() to construct.
  private HeartbeatRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HeartbeatRequest() {
    groupId_ = "";
    readerId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_HeartbeatRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_HeartbeatRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.flourine.sdk.proto.HeartbeatRequest.class, io.flourine.sdk.proto.HeartbeatRequest.Builder.class);
  }

  public static final int GROUP_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object groupId_ = "";
  /**
   * <code>string group_id = 1;</code>
   * @return The groupId.
   */
  @java.lang.Override
  public java.lang.String getGroupId() {
    java.lang.Object ref = groupId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupId_ = s;
      return s;
    }
  }
  /**
   * <code>string group_id = 1;</code>
   * @return The bytes for groupId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupIdBytes() {
    java.lang.Object ref = groupId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC_ID_FIELD_NUMBER = 2;
  private int topicId_ = 0;
  /**
   * <code>uint32 topic_id = 2;</code>
   * @return The topicId.
   */
  @java.lang.Override
  public int getTopicId() {
    return topicId_;
  }

  public static final int READER_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object readerId_ = "";
  /**
   * <code>string reader_id = 3;</code>
   * @return The readerId.
   */
  @java.lang.Override
  public java.lang.String getReaderId() {
    java.lang.Object ref = readerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      readerId_ = s;
      return s;
    }
  }
  /**
   * <code>string reader_id = 3;</code>
   * @return The bytes for readerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReaderIdBytes() {
    java.lang.Object ref = readerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      readerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENERATION_FIELD_NUMBER = 4;
  private long generation_ = 0L;
  /**
   * <code>uint64 generation = 4;</code>
   * @return The generation.
   */
  @java.lang.Override
  public long getGeneration() {
    return generation_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, groupId_);
    }
    if (topicId_ != 0) {
      output.writeUInt32(2, topicId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(readerId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, readerId_);
    }
    if (generation_ != 0L) {
      output.writeUInt64(4, generation_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, groupId_);
    }
    if (topicId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, topicId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(readerId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, readerId_);
    }
    if (generation_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, generation_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.flourine.sdk.proto.HeartbeatRequest)) {
      return super.equals(obj);
    }
    io.flourine.sdk.proto.HeartbeatRequest other = (io.flourine.sdk.proto.HeartbeatRequest) obj;

    if (!getGroupId()
        .equals(other.getGroupId())) return false;
    if (getTopicId()
        != other.getTopicId()) return false;
    if (!getReaderId()
        .equals(other.getReaderId())) return false;
    if (getGeneration()
        != other.getGeneration()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGroupId().hashCode();
    hash = (37 * hash) + TOPIC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTopicId();
    hash = (37 * hash) + READER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReaderId().hashCode();
    hash = (37 * hash) + GENERATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGeneration());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.flourine.sdk.proto.HeartbeatRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.HeartbeatRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.HeartbeatRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.HeartbeatRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.HeartbeatRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.HeartbeatRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.HeartbeatRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flourine.sdk.proto.HeartbeatRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.flourine.sdk.proto.HeartbeatRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.flourine.sdk.proto.HeartbeatRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.flourine.sdk.proto.HeartbeatRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flourine.sdk.proto.HeartbeatRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.flourine.sdk.proto.HeartbeatRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code flourine.wire.HeartbeatRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flourine.wire.HeartbeatRequest)
      io.flourine.sdk.proto.HeartbeatRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_HeartbeatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_HeartbeatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.flourine.sdk.proto.HeartbeatRequest.class, io.flourine.sdk.proto.HeartbeatRequest.Builder.class);
    }

    // Construct using io.flourine.sdk.proto.HeartbeatRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      groupId_ = "";
      topicId_ = 0;
      readerId_ = "";
      generation_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_HeartbeatRequest_descriptor;
    }

    @java.lang.Override
    public io.flourine.sdk.proto.HeartbeatRequest getDefaultInstanceForType() {
      return io.flourine.sdk.proto.HeartbeatRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.flourine.sdk.proto.HeartbeatRequest build() {
      io.flourine.sdk.proto.HeartbeatRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.flourine.sdk.proto.HeartbeatRequest buildPartial() {
      io.flourine.sdk.proto.HeartbeatRequest result = new io.flourine.sdk.proto.HeartbeatRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.flourine.sdk.proto.HeartbeatRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.groupId_ = groupId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.topicId_ = topicId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.readerId_ = readerId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.generation_ = generation_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.flourine.sdk.proto.HeartbeatRequest) {
        return mergeFrom((io.flourine.sdk.proto.HeartbeatRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.flourine.sdk.proto.HeartbeatRequest other) {
      if (other == io.flourine.sdk.proto.HeartbeatRequest.getDefaultInstance()) return this;
      if (!other.getGroupId().isEmpty()) {
        groupId_ = other.groupId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getTopicId() != 0) {
        setTopicId(other.getTopicId());
      }
      if (!other.getReaderId().isEmpty()) {
        readerId_ = other.readerId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getGeneration() != 0L) {
        setGeneration(other.getGeneration());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              groupId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              topicId_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              readerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              generation_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object groupId_ = "";
    /**
     * <code>string group_id = 1;</code>
     * @return The groupId.
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string group_id = 1;</code>
     * @return The bytes for groupId.
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string group_id = 1;</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      groupId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string group_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      groupId_ = getDefaultInstance().getGroupId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string group_id = 1;</code>
     * @param value The bytes for groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      groupId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int topicId_ ;
    /**
     * <code>uint32 topic_id = 2;</code>
     * @return The topicId.
     */
    @java.lang.Override
    public int getTopicId() {
      return topicId_;
    }
    /**
     * <code>uint32 topic_id = 2;</code>
     * @param value The topicId to set.
     * @return This builder for chaining.
     */
    public Builder setTopicId(int value) {

      topicId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 topic_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopicId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      topicId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object readerId_ = "";
    /**
     * <code>string reader_id = 3;</code>
     * @return The readerId.
     */
    public java.lang.String getReaderId() {
      java.lang.Object ref = readerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reader_id = 3;</code>
     * @return The bytes for readerId.
     */
    public com.google.protobuf.ByteString
        getReaderIdBytes() {
      java.lang.Object ref = readerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reader_id = 3;</code>
     * @param value The readerId to set.
     * @return This builder for chaining.
     */
    public Builder setReaderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      readerId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string reader_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReaderId() {
      readerId_ = getDefaultInstance().getReaderId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string reader_id = 3;</code>
     * @param value The bytes for readerId to set.
     * @return This builder for chaining.
     */
    public Builder setReaderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      readerId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private long generation_ ;
    /**
     * <code>uint64 generation = 4;</code>
     * @return The generation.
     */
    @java.lang.Override
    public long getGeneration() {
      return generation_;
    }
    /**
     * <code>uint64 generation = 4;</code>
     * @param value The generation to set.
     * @return This builder for chaining.
     */
    public Builder setGeneration(long value) {

      generation_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 generation = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGeneration() {
      bitField0_ = (bitField0_ & ~0x00000008);
      generation_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:flourine.wire.HeartbeatRequest)
  }

  // @@protoc_insertion_point(class_scope:flourine.wire.HeartbeatRequest)
  private static final io.flourine.sdk.proto.HeartbeatRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.flourine.sdk.proto.HeartbeatRequest();
  }

  public static io.flourine.sdk.proto.HeartbeatRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeartbeatRequest>
      PARSER = new com.google.protobuf.AbstractParser<HeartbeatRequest>() {
    @java.lang.Override
    public HeartbeatRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HeartbeatRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeartbeatRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.flourine.sdk.proto.HeartbeatRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

