// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flourine_wire.proto
// Protobuf Java Version: 4.33.4

package io.flourine.sdk.proto;

@com.google.protobuf.Generated
public interface JoinGroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flourine.wire.JoinGroupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group_id = 1;</code>
   * @return The groupId.
   */
  java.lang.String getGroupId();
  /**
   * <code>string group_id = 1;</code>
   * @return The bytes for groupId.
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <code>string reader_id = 2;</code>
   * @return The readerId.
   */
  java.lang.String getReaderId();
  /**
   * <code>string reader_id = 2;</code>
   * @return The bytes for readerId.
   */
  com.google.protobuf.ByteString
      getReaderIdBytes();

  /**
   * <code>repeated uint32 topic_ids = 3;</code>
   * @return A list containing the topicIds.
   */
  java.util.List<java.lang.Integer> getTopicIdsList();
  /**
   * <code>repeated uint32 topic_ids = 3;</code>
   * @return The count of topicIds.
   */
  int getTopicIdsCount();
  /**
   * <code>repeated uint32 topic_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The topicIds at the given index.
   */
  int getTopicIds(int index);
}
