// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flourine_wire.proto
// Protobuf Java Version: 4.33.4

package io.flourine.sdk.proto;

/**
 * Protobuf type {@code flourine.wire.JoinGroupRequest}
 */
@com.google.protobuf.Generated
public final class JoinGroupRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flourine.wire.JoinGroupRequest)
    JoinGroupRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "JoinGroupRequest");
  }
  // Use JoinGroupRequest.newBuilder() to construct.
  private JoinGroupRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private JoinGroupRequest() {
    groupId_ = "";
    readerId_ = "";
    topicIds_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_JoinGroupRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_JoinGroupRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.flourine.sdk.proto.JoinGroupRequest.class, io.flourine.sdk.proto.JoinGroupRequest.Builder.class);
  }

  public static final int GROUP_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object groupId_ = "";
  /**
   * <code>string group_id = 1;</code>
   * @return The groupId.
   */
  @java.lang.Override
  public java.lang.String getGroupId() {
    java.lang.Object ref = groupId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupId_ = s;
      return s;
    }
  }
  /**
   * <code>string group_id = 1;</code>
   * @return The bytes for groupId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupIdBytes() {
    java.lang.Object ref = groupId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int READER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object readerId_ = "";
  /**
   * <code>string reader_id = 2;</code>
   * @return The readerId.
   */
  @java.lang.Override
  public java.lang.String getReaderId() {
    java.lang.Object ref = readerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      readerId_ = s;
      return s;
    }
  }
  /**
   * <code>string reader_id = 2;</code>
   * @return The bytes for readerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReaderIdBytes() {
    java.lang.Object ref = readerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      readerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC_IDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList topicIds_ =
      emptyIntList();
  /**
   * <code>repeated uint32 topic_ids = 3;</code>
   * @return A list containing the topicIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getTopicIdsList() {
    return topicIds_;
  }
  /**
   * <code>repeated uint32 topic_ids = 3;</code>
   * @return The count of topicIds.
   */
  public int getTopicIdsCount() {
    return topicIds_.size();
  }
  /**
   * <code>repeated uint32 topic_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The topicIds at the given index.
   */
  public int getTopicIds(int index) {
    return topicIds_.getInt(index);
  }
  private int topicIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, groupId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(readerId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, readerId_);
    }
    if (getTopicIdsList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(topicIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < topicIds_.size(); i++) {
      output.writeUInt32NoTag(topicIds_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(groupId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, groupId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(readerId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, readerId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < topicIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(topicIds_.getInt(i));
      }
      size += dataSize;
      if (!getTopicIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      topicIdsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.flourine.sdk.proto.JoinGroupRequest)) {
      return super.equals(obj);
    }
    io.flourine.sdk.proto.JoinGroupRequest other = (io.flourine.sdk.proto.JoinGroupRequest) obj;

    if (!getGroupId()
        .equals(other.getGroupId())) return false;
    if (!getReaderId()
        .equals(other.getReaderId())) return false;
    if (!getTopicIdsList()
        .equals(other.getTopicIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGroupId().hashCode();
    hash = (37 * hash) + READER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReaderId().hashCode();
    if (getTopicIdsCount() > 0) {
      hash = (37 * hash) + TOPIC_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getTopicIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.flourine.sdk.proto.JoinGroupRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.JoinGroupRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.JoinGroupRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.JoinGroupRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.JoinGroupRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.JoinGroupRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.JoinGroupRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flourine.sdk.proto.JoinGroupRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.flourine.sdk.proto.JoinGroupRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.flourine.sdk.proto.JoinGroupRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.flourine.sdk.proto.JoinGroupRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flourine.sdk.proto.JoinGroupRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.flourine.sdk.proto.JoinGroupRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code flourine.wire.JoinGroupRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flourine.wire.JoinGroupRequest)
      io.flourine.sdk.proto.JoinGroupRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_JoinGroupRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_JoinGroupRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.flourine.sdk.proto.JoinGroupRequest.class, io.flourine.sdk.proto.JoinGroupRequest.Builder.class);
    }

    // Construct using io.flourine.sdk.proto.JoinGroupRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      groupId_ = "";
      readerId_ = "";
      topicIds_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_JoinGroupRequest_descriptor;
    }

    @java.lang.Override
    public io.flourine.sdk.proto.JoinGroupRequest getDefaultInstanceForType() {
      return io.flourine.sdk.proto.JoinGroupRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.flourine.sdk.proto.JoinGroupRequest build() {
      io.flourine.sdk.proto.JoinGroupRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.flourine.sdk.proto.JoinGroupRequest buildPartial() {
      io.flourine.sdk.proto.JoinGroupRequest result = new io.flourine.sdk.proto.JoinGroupRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.flourine.sdk.proto.JoinGroupRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.groupId_ = groupId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.readerId_ = readerId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        topicIds_.makeImmutable();
        result.topicIds_ = topicIds_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.flourine.sdk.proto.JoinGroupRequest) {
        return mergeFrom((io.flourine.sdk.proto.JoinGroupRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.flourine.sdk.proto.JoinGroupRequest other) {
      if (other == io.flourine.sdk.proto.JoinGroupRequest.getDefaultInstance()) return this;
      if (!other.getGroupId().isEmpty()) {
        groupId_ = other.groupId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getReaderId().isEmpty()) {
        readerId_ = other.readerId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.topicIds_.isEmpty()) {
        if (topicIds_.isEmpty()) {
          topicIds_ = other.topicIds_;
          topicIds_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureTopicIdsIsMutable();
          topicIds_.addAll(other.topicIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              groupId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              readerId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              int v = input.readUInt32();
              ensureTopicIdsIsMutable();
              topicIds_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureTopicIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                topicIds_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object groupId_ = "";
    /**
     * <code>string group_id = 1;</code>
     * @return The groupId.
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string group_id = 1;</code>
     * @return The bytes for groupId.
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string group_id = 1;</code>
     * @param value The groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      groupId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string group_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupId() {
      groupId_ = getDefaultInstance().getGroupId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string group_id = 1;</code>
     * @param value The bytes for groupId to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      groupId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object readerId_ = "";
    /**
     * <code>string reader_id = 2;</code>
     * @return The readerId.
     */
    public java.lang.String getReaderId() {
      java.lang.Object ref = readerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readerId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reader_id = 2;</code>
     * @return The bytes for readerId.
     */
    public com.google.protobuf.ByteString
        getReaderIdBytes() {
      java.lang.Object ref = readerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reader_id = 2;</code>
     * @param value The readerId to set.
     * @return This builder for chaining.
     */
    public Builder setReaderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      readerId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string reader_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReaderId() {
      readerId_ = getDefaultInstance().getReaderId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string reader_id = 2;</code>
     * @param value The bytes for readerId to set.
     * @return This builder for chaining.
     */
    public Builder setReaderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      readerId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList topicIds_ = emptyIntList();
    private void ensureTopicIdsIsMutable() {
      if (!topicIds_.isModifiable()) {
        topicIds_ = makeMutableCopy(topicIds_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated uint32 topic_ids = 3;</code>
     * @return A list containing the topicIds.
     */
    public java.util.List<java.lang.Integer>
        getTopicIdsList() {
      topicIds_.makeImmutable();
      return topicIds_;
    }
    /**
     * <code>repeated uint32 topic_ids = 3;</code>
     * @return The count of topicIds.
     */
    public int getTopicIdsCount() {
      return topicIds_.size();
    }
    /**
     * <code>repeated uint32 topic_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The topicIds at the given index.
     */
    public int getTopicIds(int index) {
      return topicIds_.getInt(index);
    }
    /**
     * <code>repeated uint32 topic_ids = 3;</code>
     * @param index The index to set the value at.
     * @param value The topicIds to set.
     * @return This builder for chaining.
     */
    public Builder setTopicIds(
        int index, int value) {

      ensureTopicIdsIsMutable();
      topicIds_.setInt(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 topic_ids = 3;</code>
     * @param value The topicIds to add.
     * @return This builder for chaining.
     */
    public Builder addTopicIds(int value) {

      ensureTopicIdsIsMutable();
      topicIds_.addInt(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 topic_ids = 3;</code>
     * @param values The topicIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllTopicIds(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureTopicIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, topicIds_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated uint32 topic_ids = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopicIds() {
      topicIds_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:flourine.wire.JoinGroupRequest)
  }

  // @@protoc_insertion_point(class_scope:flourine.wire.JoinGroupRequest)
  private static final io.flourine.sdk.proto.JoinGroupRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.flourine.sdk.proto.JoinGroupRequest();
  }

  public static io.flourine.sdk.proto.JoinGroupRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JoinGroupRequest>
      PARSER = new com.google.protobuf.AbstractParser<JoinGroupRequest>() {
    @java.lang.Override
    public JoinGroupRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JoinGroupRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JoinGroupRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.flourine.sdk.proto.JoinGroupRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

