// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flourine_wire.proto
// Protobuf Java Version: 4.33.4

package io.flourine.sdk.proto;

/**
 * Protobuf type {@code flourine.wire.PollResponse}
 */
@com.google.protobuf.Generated
public final class PollResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:flourine.wire.PollResponse)
    PollResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "PollResponse");
  }
  // Use PollResponse.newBuilder() to construct.
  private PollResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PollResponse() {
    errorMessage_ = "";
    results_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_PollResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_PollResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.flourine.sdk.proto.PollResponse.class, io.flourine.sdk.proto.PollResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int ERROR_CODE_FIELD_NUMBER = 2;
  private int errorCode_ = 0;
  /**
   * <code>uint32 error_code = 2;</code>
   * @return The errorCode.
   */
  @java.lang.Override
  public int getErrorCode() {
    return errorCode_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESULTS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<io.flourine.sdk.proto.TopicResult> results_;
  /**
   * <code>repeated .flourine.wire.TopicResult results = 4;</code>
   */
  @java.lang.Override
  public java.util.List<io.flourine.sdk.proto.TopicResult> getResultsList() {
    return results_;
  }
  /**
   * <code>repeated .flourine.wire.TopicResult results = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.flourine.sdk.proto.TopicResultOrBuilder> 
      getResultsOrBuilderList() {
    return results_;
  }
  /**
   * <code>repeated .flourine.wire.TopicResult results = 4;</code>
   */
  @java.lang.Override
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <code>repeated .flourine.wire.TopicResult results = 4;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.TopicResult getResults(int index) {
    return results_.get(index);
  }
  /**
   * <code>repeated .flourine.wire.TopicResult results = 4;</code>
   */
  @java.lang.Override
  public io.flourine.sdk.proto.TopicResultOrBuilder getResultsOrBuilder(
      int index) {
    return results_.get(index);
  }

  public static final int START_OFFSET_FIELD_NUMBER = 5;
  private long startOffset_ = 0L;
  /**
   * <code>uint64 start_offset = 5;</code>
   * @return The startOffset.
   */
  @java.lang.Override
  public long getStartOffset() {
    return startOffset_;
  }

  public static final int END_OFFSET_FIELD_NUMBER = 6;
  private long endOffset_ = 0L;
  /**
   * <code>uint64 end_offset = 6;</code>
   * @return The endOffset.
   */
  @java.lang.Override
  public long getEndOffset() {
    return endOffset_;
  }

  public static final int LEASE_DEADLINE_MS_FIELD_NUMBER = 7;
  private long leaseDeadlineMs_ = 0L;
  /**
   * <code>uint64 lease_deadline_ms = 7;</code>
   * @return The leaseDeadlineMs.
   */
  @java.lang.Override
  public long getLeaseDeadlineMs() {
    return leaseDeadlineMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (errorCode_ != 0) {
      output.writeUInt32(2, errorCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, errorMessage_);
    }
    for (int i = 0; i < results_.size(); i++) {
      output.writeMessage(4, results_.get(i));
    }
    if (startOffset_ != 0L) {
      output.writeUInt64(5, startOffset_);
    }
    if (endOffset_ != 0L) {
      output.writeUInt64(6, endOffset_);
    }
    if (leaseDeadlineMs_ != 0L) {
      output.writeUInt64(7, leaseDeadlineMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (errorCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, errorCode_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, errorMessage_);
    }
    for (int i = 0; i < results_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, results_.get(i));
    }
    if (startOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, startOffset_);
    }
    if (endOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, endOffset_);
    }
    if (leaseDeadlineMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, leaseDeadlineMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.flourine.sdk.proto.PollResponse)) {
      return super.equals(obj);
    }
    io.flourine.sdk.proto.PollResponse other = (io.flourine.sdk.proto.PollResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (getErrorCode()
        != other.getErrorCode()) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (!getResultsList()
        .equals(other.getResultsList())) return false;
    if (getStartOffset()
        != other.getStartOffset()) return false;
    if (getEndOffset()
        != other.getEndOffset()) return false;
    if (getLeaseDeadlineMs()
        != other.getLeaseDeadlineMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + ERROR_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorCode();
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    hash = (37 * hash) + START_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartOffset());
    hash = (37 * hash) + END_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndOffset());
    hash = (37 * hash) + LEASE_DEADLINE_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLeaseDeadlineMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.flourine.sdk.proto.PollResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.PollResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.PollResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.PollResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.PollResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.flourine.sdk.proto.PollResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.flourine.sdk.proto.PollResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flourine.sdk.proto.PollResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.flourine.sdk.proto.PollResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.flourine.sdk.proto.PollResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.flourine.sdk.proto.PollResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.flourine.sdk.proto.PollResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.flourine.sdk.proto.PollResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code flourine.wire.PollResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:flourine.wire.PollResponse)
      io.flourine.sdk.proto.PollResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_PollResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_PollResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.flourine.sdk.proto.PollResponse.class, io.flourine.sdk.proto.PollResponse.Builder.class);
    }

    // Construct using io.flourine.sdk.proto.PollResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      errorCode_ = 0;
      errorMessage_ = "";
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
      } else {
        results_ = null;
        resultsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      startOffset_ = 0L;
      endOffset_ = 0L;
      leaseDeadlineMs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.flourine.sdk.proto.FlourineWire.internal_static_flourine_wire_PollResponse_descriptor;
    }

    @java.lang.Override
    public io.flourine.sdk.proto.PollResponse getDefaultInstanceForType() {
      return io.flourine.sdk.proto.PollResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.flourine.sdk.proto.PollResponse build() {
      io.flourine.sdk.proto.PollResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.flourine.sdk.proto.PollResponse buildPartial() {
      io.flourine.sdk.proto.PollResponse result = new io.flourine.sdk.proto.PollResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.flourine.sdk.proto.PollResponse result) {
      if (resultsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
    }

    private void buildPartial0(io.flourine.sdk.proto.PollResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.errorCode_ = errorCode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.startOffset_ = startOffset_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.endOffset_ = endOffset_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.leaseDeadlineMs_ = leaseDeadlineMs_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.flourine.sdk.proto.PollResponse) {
        return mergeFrom((io.flourine.sdk.proto.PollResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.flourine.sdk.proto.PollResponse other) {
      if (other == io.flourine.sdk.proto.PollResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.getErrorCode() != 0) {
        setErrorCode(other.getErrorCode());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (resultsBuilder_ == null) {
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
      } else {
        if (!other.results_.isEmpty()) {
          if (resultsBuilder_.isEmpty()) {
            resultsBuilder_.dispose();
            resultsBuilder_ = null;
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000008);
            resultsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetResultsFieldBuilder() : null;
          } else {
            resultsBuilder_.addAllMessages(other.results_);
          }
        }
      }
      if (other.getStartOffset() != 0L) {
        setStartOffset(other.getStartOffset());
      }
      if (other.getEndOffset() != 0L) {
        setEndOffset(other.getEndOffset());
      }
      if (other.getLeaseDeadlineMs() != 0L) {
        setLeaseDeadlineMs(other.getLeaseDeadlineMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              errorCode_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              io.flourine.sdk.proto.TopicResult m =
                  input.readMessage(
                      io.flourine.sdk.proto.TopicResult.parser(),
                      extensionRegistry);
              if (resultsBuilder_ == null) {
                ensureResultsIsMutable();
                results_.add(m);
              } else {
                resultsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 40: {
              startOffset_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              endOffset_ = input.readUInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              leaseDeadlineMs_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private int errorCode_ ;
    /**
     * <code>uint32 error_code = 2;</code>
     * @return The errorCode.
     */
    @java.lang.Override
    public int getErrorCode() {
      return errorCode_;
    }
    /**
     * <code>uint32 error_code = 2;</code>
     * @param value The errorCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrorCode(int value) {

      errorCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 error_code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorCode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      errorCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 3;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_message = 3;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_message = 3;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string error_message = 3;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<io.flourine.sdk.proto.TopicResult> results_ =
      java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        results_ = new java.util.ArrayList<io.flourine.sdk.proto.TopicResult>(results_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.flourine.sdk.proto.TopicResult, io.flourine.sdk.proto.TopicResult.Builder, io.flourine.sdk.proto.TopicResultOrBuilder> resultsBuilder_;

    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public java.util.List<io.flourine.sdk.proto.TopicResult> getResultsList() {
      if (resultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(results_);
      } else {
        return resultsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public int getResultsCount() {
      if (resultsBuilder_ == null) {
        return results_.size();
      } else {
        return resultsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public io.flourine.sdk.proto.TopicResult getResults(int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);
      } else {
        return resultsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public Builder setResults(
        int index, io.flourine.sdk.proto.TopicResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public Builder setResults(
        int index, io.flourine.sdk.proto.TopicResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public Builder addResults(io.flourine.sdk.proto.TopicResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public Builder addResults(
        int index, io.flourine.sdk.proto.TopicResult value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public Builder addResults(
        io.flourine.sdk.proto.TopicResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public Builder addResults(
        int index, io.flourine.sdk.proto.TopicResult.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public Builder addAllResults(
        java.lang.Iterable<? extends io.flourine.sdk.proto.TopicResult> values) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
      } else {
        resultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public Builder removeResults(int index) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.remove(index);
        onChanged();
      } else {
        resultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public io.flourine.sdk.proto.TopicResult.Builder getResultsBuilder(
        int index) {
      return internalGetResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public io.flourine.sdk.proto.TopicResultOrBuilder getResultsOrBuilder(
        int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);  } else {
        return resultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public java.util.List<? extends io.flourine.sdk.proto.TopicResultOrBuilder> 
         getResultsOrBuilderList() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(results_);
      }
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public io.flourine.sdk.proto.TopicResult.Builder addResultsBuilder() {
      return internalGetResultsFieldBuilder().addBuilder(
          io.flourine.sdk.proto.TopicResult.getDefaultInstance());
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public io.flourine.sdk.proto.TopicResult.Builder addResultsBuilder(
        int index) {
      return internalGetResultsFieldBuilder().addBuilder(
          index, io.flourine.sdk.proto.TopicResult.getDefaultInstance());
    }
    /**
     * <code>repeated .flourine.wire.TopicResult results = 4;</code>
     */
    public java.util.List<io.flourine.sdk.proto.TopicResult.Builder> 
         getResultsBuilderList() {
      return internalGetResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.flourine.sdk.proto.TopicResult, io.flourine.sdk.proto.TopicResult.Builder, io.flourine.sdk.proto.TopicResultOrBuilder> 
        internalGetResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.flourine.sdk.proto.TopicResult, io.flourine.sdk.proto.TopicResult.Builder, io.flourine.sdk.proto.TopicResultOrBuilder>(
                results_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }

    private long startOffset_ ;
    /**
     * <code>uint64 start_offset = 5;</code>
     * @return The startOffset.
     */
    @java.lang.Override
    public long getStartOffset() {
      return startOffset_;
    }
    /**
     * <code>uint64 start_offset = 5;</code>
     * @param value The startOffset to set.
     * @return This builder for chaining.
     */
    public Builder setStartOffset(long value) {

      startOffset_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 start_offset = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartOffset() {
      bitField0_ = (bitField0_ & ~0x00000010);
      startOffset_ = 0L;
      onChanged();
      return this;
    }

    private long endOffset_ ;
    /**
     * <code>uint64 end_offset = 6;</code>
     * @return The endOffset.
     */
    @java.lang.Override
    public long getEndOffset() {
      return endOffset_;
    }
    /**
     * <code>uint64 end_offset = 6;</code>
     * @param value The endOffset to set.
     * @return This builder for chaining.
     */
    public Builder setEndOffset(long value) {

      endOffset_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 end_offset = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndOffset() {
      bitField0_ = (bitField0_ & ~0x00000020);
      endOffset_ = 0L;
      onChanged();
      return this;
    }

    private long leaseDeadlineMs_ ;
    /**
     * <code>uint64 lease_deadline_ms = 7;</code>
     * @return The leaseDeadlineMs.
     */
    @java.lang.Override
    public long getLeaseDeadlineMs() {
      return leaseDeadlineMs_;
    }
    /**
     * <code>uint64 lease_deadline_ms = 7;</code>
     * @param value The leaseDeadlineMs to set.
     * @return This builder for chaining.
     */
    public Builder setLeaseDeadlineMs(long value) {

      leaseDeadlineMs_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 lease_deadline_ms = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLeaseDeadlineMs() {
      bitField0_ = (bitField0_ & ~0x00000040);
      leaseDeadlineMs_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:flourine.wire.PollResponse)
  }

  // @@protoc_insertion_point(class_scope:flourine.wire.PollResponse)
  private static final io.flourine.sdk.proto.PollResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.flourine.sdk.proto.PollResponse();
  }

  public static io.flourine.sdk.proto.PollResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PollResponse>
      PARSER = new com.google.protobuf.AbstractParser<PollResponse>() {
    @java.lang.Override
    public PollResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PollResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PollResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.flourine.sdk.proto.PollResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

