// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flourine_wire.proto
// Protobuf Java Version: 4.33.4

package io.flourine.sdk.proto;

@com.google.protobuf.Generated
public interface RejoinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flourine.wire.RejoinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>uint32 error_code = 2;</code>
   * @return The errorCode.
   */
  int getErrorCode();

  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>uint64 generation = 4;</code>
   * @return The generation.
   */
  long getGeneration();

  /**
   * <code>.flourine.wire.RejoinStatus status = 5;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.flourine.wire.RejoinStatus status = 5;</code>
   * @return The status.
   */
  io.flourine.sdk.proto.RejoinStatus getStatus();

  /**
   * <code>repeated .flourine.wire.PartitionAssignment assignments = 6;</code>
   */
  java.util.List<io.flourine.sdk.proto.PartitionAssignment> 
      getAssignmentsList();
  /**
   * <code>repeated .flourine.wire.PartitionAssignment assignments = 6;</code>
   */
  io.flourine.sdk.proto.PartitionAssignment getAssignments(int index);
  /**
   * <code>repeated .flourine.wire.PartitionAssignment assignments = 6;</code>
   */
  int getAssignmentsCount();
  /**
   * <code>repeated .flourine.wire.PartitionAssignment assignments = 6;</code>
   */
  java.util.List<? extends io.flourine.sdk.proto.PartitionAssignmentOrBuilder> 
      getAssignmentsOrBuilderList();
  /**
   * <code>repeated .flourine.wire.PartitionAssignment assignments = 6;</code>
   */
  io.flourine.sdk.proto.PartitionAssignmentOrBuilder getAssignmentsOrBuilder(
      int index);
}
