// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flourine_wire.proto
// Protobuf Java Version: 4.33.4

package io.flourine.sdk.proto;

/**
 * Protobuf enum {@code flourine.wire.RejoinStatus}
 */
@com.google.protobuf.Generated
public enum RejoinStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>REJOIN_STATUS_OK = 0;</code>
   */
  REJOIN_STATUS_OK(0),
  /**
   * <code>REJOIN_STATUS_REBALANCE_NEEDED = 1;</code>
   */
  REJOIN_STATUS_REBALANCE_NEEDED(1),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "RejoinStatus");
  }
  /**
   * <code>REJOIN_STATUS_OK = 0;</code>
   */
  public static final int REJOIN_STATUS_OK_VALUE = 0;
  /**
   * <code>REJOIN_STATUS_REBALANCE_NEEDED = 1;</code>
   */
  public static final int REJOIN_STATUS_REBALANCE_NEEDED_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RejoinStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RejoinStatus forNumber(int value) {
    switch (value) {
      case 0: return REJOIN_STATUS_OK;
      case 1: return REJOIN_STATUS_REBALANCE_NEEDED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RejoinStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RejoinStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RejoinStatus>() {
          public RejoinStatus findValueByNumber(int number) {
            return RejoinStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.flourine.sdk.proto.FlourineWire.getDescriptor().getEnumTypes().get(1);
  }

  private static final RejoinStatus[] VALUES = values();

  public static RejoinStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RejoinStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:flourine.wire.RejoinStatus)
}

