// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: flourine_wire.proto
// Protobuf Java Version: 4.33.4

package io.flourine.sdk.proto;

@com.google.protobuf.Generated
public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:flourine.wire.ServerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.flourine.wire.AppendResponse append = 1;</code>
   * @return Whether the append field is set.
   */
  boolean hasAppend();
  /**
   * <code>.flourine.wire.AppendResponse append = 1;</code>
   * @return The append.
   */
  io.flourine.sdk.proto.AppendResponse getAppend();
  /**
   * <code>.flourine.wire.AppendResponse append = 1;</code>
   */
  io.flourine.sdk.proto.AppendResponseOrBuilder getAppendOrBuilder();

  /**
   * <code>.flourine.wire.ReadResponse read = 2;</code>
   * @return Whether the read field is set.
   */
  boolean hasRead();
  /**
   * <code>.flourine.wire.ReadResponse read = 2;</code>
   * @return The read.
   */
  io.flourine.sdk.proto.ReadResponse getRead();
  /**
   * <code>.flourine.wire.ReadResponse read = 2;</code>
   */
  io.flourine.sdk.proto.ReadResponseOrBuilder getReadOrBuilder();

  /**
   * <code>.flourine.wire.JoinGroupResponse join_group = 3;</code>
   * @return Whether the joinGroup field is set.
   */
  boolean hasJoinGroup();
  /**
   * <code>.flourine.wire.JoinGroupResponse join_group = 3;</code>
   * @return The joinGroup.
   */
  io.flourine.sdk.proto.JoinGroupResponse getJoinGroup();
  /**
   * <code>.flourine.wire.JoinGroupResponse join_group = 3;</code>
   */
  io.flourine.sdk.proto.JoinGroupResponseOrBuilder getJoinGroupOrBuilder();

  /**
   * <code>.flourine.wire.HeartbeatResponse heartbeat = 4;</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <code>.flourine.wire.HeartbeatResponse heartbeat = 4;</code>
   * @return The heartbeat.
   */
  io.flourine.sdk.proto.HeartbeatResponse getHeartbeat();
  /**
   * <code>.flourine.wire.HeartbeatResponse heartbeat = 4;</code>
   */
  io.flourine.sdk.proto.HeartbeatResponseOrBuilder getHeartbeatOrBuilder();

  /**
   * <code>.flourine.wire.PollResponse poll = 5;</code>
   * @return Whether the poll field is set.
   */
  boolean hasPoll();
  /**
   * <code>.flourine.wire.PollResponse poll = 5;</code>
   * @return The poll.
   */
  io.flourine.sdk.proto.PollResponse getPoll();
  /**
   * <code>.flourine.wire.PollResponse poll = 5;</code>
   */
  io.flourine.sdk.proto.PollResponseOrBuilder getPollOrBuilder();

  /**
   * <code>.flourine.wire.LeaveGroupResponse leave_group = 6;</code>
   * @return Whether the leaveGroup field is set.
   */
  boolean hasLeaveGroup();
  /**
   * <code>.flourine.wire.LeaveGroupResponse leave_group = 6;</code>
   * @return The leaveGroup.
   */
  io.flourine.sdk.proto.LeaveGroupResponse getLeaveGroup();
  /**
   * <code>.flourine.wire.LeaveGroupResponse leave_group = 6;</code>
   */
  io.flourine.sdk.proto.LeaveGroupResponseOrBuilder getLeaveGroupOrBuilder();

  /**
   * <code>.flourine.wire.CommitResponse commit = 7;</code>
   * @return Whether the commit field is set.
   */
  boolean hasCommit();
  /**
   * <code>.flourine.wire.CommitResponse commit = 7;</code>
   * @return The commit.
   */
  io.flourine.sdk.proto.CommitResponse getCommit();
  /**
   * <code>.flourine.wire.CommitResponse commit = 7;</code>
   */
  io.flourine.sdk.proto.CommitResponseOrBuilder getCommitOrBuilder();

  /**
   * <code>.flourine.wire.AuthResponse auth = 8;</code>
   * @return Whether the auth field is set.
   */
  boolean hasAuth();
  /**
   * <code>.flourine.wire.AuthResponse auth = 8;</code>
   * @return The auth.
   */
  io.flourine.sdk.proto.AuthResponse getAuth();
  /**
   * <code>.flourine.wire.AuthResponse auth = 8;</code>
   */
  io.flourine.sdk.proto.AuthResponseOrBuilder getAuthOrBuilder();

  io.flourine.sdk.proto.ServerMessage.MessageCase getMessageCase();
}
