// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: turbine_wire.proto
// Protobuf Java Version: 4.33.4

package io.turbine.sdk.proto;

/**
 * Protobuf type {@code turbine.wire.BatchAck}
 */
@com.google.protobuf.Generated
public final class BatchAck extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:turbine.wire.BatchAck)
    BatchAckOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "BatchAck");
  }
  // Use BatchAck.newBuilder() to construct.
  private BatchAck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BatchAck() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.turbine.sdk.proto.TurbineWire.internal_static_turbine_wire_BatchAck_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.turbine.sdk.proto.TurbineWire.internal_static_turbine_wire_BatchAck_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.turbine.sdk.proto.BatchAck.class, io.turbine.sdk.proto.BatchAck.Builder.class);
  }

  public static final int TOPIC_ID_FIELD_NUMBER = 1;
  private int topicId_ = 0;
  /**
   * <code>uint32 topic_id = 1;</code>
   * @return The topicId.
   */
  @java.lang.Override
  public int getTopicId() {
    return topicId_;
  }

  public static final int PARTITION_ID_FIELD_NUMBER = 2;
  private int partitionId_ = 0;
  /**
   * <code>uint32 partition_id = 2;</code>
   * @return The partitionId.
   */
  @java.lang.Override
  public int getPartitionId() {
    return partitionId_;
  }

  public static final int SCHEMA_ID_FIELD_NUMBER = 3;
  private int schemaId_ = 0;
  /**
   * <code>uint32 schema_id = 3;</code>
   * @return The schemaId.
   */
  @java.lang.Override
  public int getSchemaId() {
    return schemaId_;
  }

  public static final int START_OFFSET_FIELD_NUMBER = 4;
  private long startOffset_ = 0L;
  /**
   * <code>uint64 start_offset = 4;</code>
   * @return The startOffset.
   */
  @java.lang.Override
  public long getStartOffset() {
    return startOffset_;
  }

  public static final int END_OFFSET_FIELD_NUMBER = 5;
  private long endOffset_ = 0L;
  /**
   * <code>uint64 end_offset = 5;</code>
   * @return The endOffset.
   */
  @java.lang.Override
  public long getEndOffset() {
    return endOffset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (topicId_ != 0) {
      output.writeUInt32(1, topicId_);
    }
    if (partitionId_ != 0) {
      output.writeUInt32(2, partitionId_);
    }
    if (schemaId_ != 0) {
      output.writeUInt32(3, schemaId_);
    }
    if (startOffset_ != 0L) {
      output.writeUInt64(4, startOffset_);
    }
    if (endOffset_ != 0L) {
      output.writeUInt64(5, endOffset_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (topicId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, topicId_);
    }
    if (partitionId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, partitionId_);
    }
    if (schemaId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, schemaId_);
    }
    if (startOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, startOffset_);
    }
    if (endOffset_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, endOffset_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.turbine.sdk.proto.BatchAck)) {
      return super.equals(obj);
    }
    io.turbine.sdk.proto.BatchAck other = (io.turbine.sdk.proto.BatchAck) obj;

    if (getTopicId()
        != other.getTopicId()) return false;
    if (getPartitionId()
        != other.getPartitionId()) return false;
    if (getSchemaId()
        != other.getSchemaId()) return false;
    if (getStartOffset()
        != other.getStartOffset()) return false;
    if (getEndOffset()
        != other.getEndOffset()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPIC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTopicId();
    hash = (37 * hash) + PARTITION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPartitionId();
    hash = (37 * hash) + SCHEMA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaId();
    hash = (37 * hash) + START_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartOffset());
    hash = (37 * hash) + END_OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndOffset());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.turbine.sdk.proto.BatchAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.turbine.sdk.proto.BatchAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.turbine.sdk.proto.BatchAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.turbine.sdk.proto.BatchAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.turbine.sdk.proto.BatchAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.turbine.sdk.proto.BatchAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.turbine.sdk.proto.BatchAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.turbine.sdk.proto.BatchAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.turbine.sdk.proto.BatchAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.turbine.sdk.proto.BatchAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.turbine.sdk.proto.BatchAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.turbine.sdk.proto.BatchAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.turbine.sdk.proto.BatchAck prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code turbine.wire.BatchAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:turbine.wire.BatchAck)
      io.turbine.sdk.proto.BatchAckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.turbine.sdk.proto.TurbineWire.internal_static_turbine_wire_BatchAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.turbine.sdk.proto.TurbineWire.internal_static_turbine_wire_BatchAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.turbine.sdk.proto.BatchAck.class, io.turbine.sdk.proto.BatchAck.Builder.class);
    }

    // Construct using io.turbine.sdk.proto.BatchAck.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      topicId_ = 0;
      partitionId_ = 0;
      schemaId_ = 0;
      startOffset_ = 0L;
      endOffset_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.turbine.sdk.proto.TurbineWire.internal_static_turbine_wire_BatchAck_descriptor;
    }

    @java.lang.Override
    public io.turbine.sdk.proto.BatchAck getDefaultInstanceForType() {
      return io.turbine.sdk.proto.BatchAck.getDefaultInstance();
    }

    @java.lang.Override
    public io.turbine.sdk.proto.BatchAck build() {
      io.turbine.sdk.proto.BatchAck result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.turbine.sdk.proto.BatchAck buildPartial() {
      io.turbine.sdk.proto.BatchAck result = new io.turbine.sdk.proto.BatchAck(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.turbine.sdk.proto.BatchAck result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.topicId_ = topicId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.partitionId_ = partitionId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.schemaId_ = schemaId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.startOffset_ = startOffset_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.endOffset_ = endOffset_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.turbine.sdk.proto.BatchAck) {
        return mergeFrom((io.turbine.sdk.proto.BatchAck)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.turbine.sdk.proto.BatchAck other) {
      if (other == io.turbine.sdk.proto.BatchAck.getDefaultInstance()) return this;
      if (other.getTopicId() != 0) {
        setTopicId(other.getTopicId());
      }
      if (other.getPartitionId() != 0) {
        setPartitionId(other.getPartitionId());
      }
      if (other.getSchemaId() != 0) {
        setSchemaId(other.getSchemaId());
      }
      if (other.getStartOffset() != 0L) {
        setStartOffset(other.getStartOffset());
      }
      if (other.getEndOffset() != 0L) {
        setEndOffset(other.getEndOffset());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              topicId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              partitionId_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              schemaId_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              startOffset_ = input.readUInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              endOffset_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int topicId_ ;
    /**
     * <code>uint32 topic_id = 1;</code>
     * @return The topicId.
     */
    @java.lang.Override
    public int getTopicId() {
      return topicId_;
    }
    /**
     * <code>uint32 topic_id = 1;</code>
     * @param value The topicId to set.
     * @return This builder for chaining.
     */
    public Builder setTopicId(int value) {

      topicId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 topic_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopicId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      topicId_ = 0;
      onChanged();
      return this;
    }

    private int partitionId_ ;
    /**
     * <code>uint32 partition_id = 2;</code>
     * @return The partitionId.
     */
    @java.lang.Override
    public int getPartitionId() {
      return partitionId_;
    }
    /**
     * <code>uint32 partition_id = 2;</code>
     * @param value The partitionId to set.
     * @return This builder for chaining.
     */
    public Builder setPartitionId(int value) {

      partitionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 partition_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartitionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      partitionId_ = 0;
      onChanged();
      return this;
    }

    private int schemaId_ ;
    /**
     * <code>uint32 schema_id = 3;</code>
     * @return The schemaId.
     */
    @java.lang.Override
    public int getSchemaId() {
      return schemaId_;
    }
    /**
     * <code>uint32 schema_id = 3;</code>
     * @param value The schemaId to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaId(int value) {

      schemaId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 schema_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      schemaId_ = 0;
      onChanged();
      return this;
    }

    private long startOffset_ ;
    /**
     * <code>uint64 start_offset = 4;</code>
     * @return The startOffset.
     */
    @java.lang.Override
    public long getStartOffset() {
      return startOffset_;
    }
    /**
     * <code>uint64 start_offset = 4;</code>
     * @param value The startOffset to set.
     * @return This builder for chaining.
     */
    public Builder setStartOffset(long value) {

      startOffset_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 start_offset = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartOffset() {
      bitField0_ = (bitField0_ & ~0x00000008);
      startOffset_ = 0L;
      onChanged();
      return this;
    }

    private long endOffset_ ;
    /**
     * <code>uint64 end_offset = 5;</code>
     * @return The endOffset.
     */
    @java.lang.Override
    public long getEndOffset() {
      return endOffset_;
    }
    /**
     * <code>uint64 end_offset = 5;</code>
     * @param value The endOffset to set.
     * @return This builder for chaining.
     */
    public Builder setEndOffset(long value) {

      endOffset_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 end_offset = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndOffset() {
      bitField0_ = (bitField0_ & ~0x00000010);
      endOffset_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:turbine.wire.BatchAck)
  }

  // @@protoc_insertion_point(class_scope:turbine.wire.BatchAck)
  private static final io.turbine.sdk.proto.BatchAck DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.turbine.sdk.proto.BatchAck();
  }

  public static io.turbine.sdk.proto.BatchAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchAck>
      PARSER = new com.google.protobuf.AbstractParser<BatchAck>() {
    @java.lang.Override
    public BatchAck parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatchAck> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchAck> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.turbine.sdk.proto.BatchAck getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

