// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: turbine_wire.proto
// Protobuf Java Version: 4.33.4

package io.turbine.sdk.proto;

@com.google.protobuf.Generated
public interface BatchAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:turbine.wire.BatchAck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 topic_id = 1;</code>
   * @return The topicId.
   */
  int getTopicId();

  /**
   * <code>uint32 partition_id = 2;</code>
   * @return The partitionId.
   */
  int getPartitionId();

  /**
   * <code>uint32 schema_id = 3;</code>
   * @return The schemaId.
   */
  int getSchemaId();

  /**
   * <code>uint64 start_offset = 4;</code>
   * @return The startOffset.
   */
  long getStartOffset();

  /**
   * <code>uint64 end_offset = 5;</code>
   * @return The endOffset.
   */
  long getEndOffset();
}
