// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: turbine_wire.proto
// Protobuf Java Version: 4.33.4

package io.turbine.sdk.proto;

@com.google.protobuf.Generated
public interface PartitionAssignmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:turbine.wire.PartitionAssignment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 topic_id = 1;</code>
   * @return The topicId.
   */
  int getTopicId();

  /**
   * <code>uint32 partition_id = 2;</code>
   * @return The partitionId.
   */
  int getPartitionId();

  /**
   * <code>uint64 committed_offset = 3;</code>
   * @return The committedOffset.
   */
  long getCommittedOffset();
}
