// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: turbine_wire.proto
// Protobuf Java Version: 4.33.4

package io.turbine.sdk.proto;

@com.google.protobuf.Generated
public interface ReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:turbine.wire.ReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string group_id = 1;</code>
   * @return The groupId.
   */
  java.lang.String getGroupId();
  /**
   * <code>string group_id = 1;</code>
   * @return The bytes for groupId.
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <code>string reader_id = 2;</code>
   * @return The readerId.
   */
  java.lang.String getReaderId();
  /**
   * <code>string reader_id = 2;</code>
   * @return The bytes for readerId.
   */
  com.google.protobuf.ByteString
      getReaderIdBytes();

  /**
   * <code>uint64 generation = 3;</code>
   * @return The generation.
   */
  long getGeneration();

  /**
   * <code>repeated .turbine.wire.PartitionRead reads = 4;</code>
   */
  java.util.List<io.turbine.sdk.proto.PartitionRead> 
      getReadsList();
  /**
   * <code>repeated .turbine.wire.PartitionRead reads = 4;</code>
   */
  io.turbine.sdk.proto.PartitionRead getReads(int index);
  /**
   * <code>repeated .turbine.wire.PartitionRead reads = 4;</code>
   */
  int getReadsCount();
  /**
   * <code>repeated .turbine.wire.PartitionRead reads = 4;</code>
   */
  java.util.List<? extends io.turbine.sdk.proto.PartitionReadOrBuilder> 
      getReadsOrBuilderList();
  /**
   * <code>repeated .turbine.wire.PartitionRead reads = 4;</code>
   */
  io.turbine.sdk.proto.PartitionReadOrBuilder getReadsOrBuilder(
      int index);
}
