// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: turbine_wire.proto
// Protobuf Java Version: 4.33.4

package io.turbine.sdk.proto;

@com.google.protobuf.Generated
public interface RecordBatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:turbine.wire.RecordBatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 topic_id = 1;</code>
   * @return The topicId.
   */
  int getTopicId();

  /**
   * <code>uint32 partition_id = 2;</code>
   * @return The partitionId.
   */
  int getPartitionId();

  /**
   * <code>uint32 schema_id = 3;</code>
   * @return The schemaId.
   */
  int getSchemaId();

  /**
   * <code>repeated .turbine.wire.Record records = 4;</code>
   */
  java.util.List<io.turbine.sdk.proto.Record> 
      getRecordsList();
  /**
   * <code>repeated .turbine.wire.Record records = 4;</code>
   */
  io.turbine.sdk.proto.Record getRecords(int index);
  /**
   * <code>repeated .turbine.wire.Record records = 4;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .turbine.wire.Record records = 4;</code>
   */
  java.util.List<? extends io.turbine.sdk.proto.RecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .turbine.wire.Record records = 4;</code>
   */
  io.turbine.sdk.proto.RecordOrBuilder getRecordsOrBuilder(
      int index);
}
