// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: turbine_wire.proto
// Protobuf Java Version: 4.33.4

package io.turbine.sdk.proto;

@com.google.protobuf.Generated
public final class TurbineWire extends com.google.protobuf.GeneratedFile {
  private TurbineWire() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "TurbineWire");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_Record_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_Record_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_RecordBatch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_RecordBatch_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_BatchAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_BatchAck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_AppendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_AppendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_AppendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_AppendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_PartitionRead_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_PartitionRead_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_PartitionResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_PartitionResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_ReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_ReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_JoinGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_JoinGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_PartitionAssignment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_PartitionAssignment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_JoinGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_JoinGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_HeartbeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_RejoinRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_RejoinRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_RejoinResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_RejoinResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_LeaveGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_LeaveGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_LeaveGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_LeaveGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_PartitionCommit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_PartitionCommit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_CommitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_CommitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_CommitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_AuthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_AuthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_AuthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_AuthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_turbine_wire_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_turbine_wire_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022turbine_wire.proto\022\014turbine.wire\"1\n\006Re" +
      "cord\022\020\n\003key\030\001 \001(\014H\000\210\001\001\022\r\n\005value\030\002 \001(\014B\006\n" +
      "\004_key\"o\n\013RecordBatch\022\020\n\010topic_id\030\001 \001(\r\022\024" +
      "\n\014partition_id\030\002 \001(\r\022\021\n\tschema_id\030\003 \001(\r\022" +
      "%\n\007records\030\004 \003(\0132\024.turbine.wire.Record\"o" +
      "\n\010BatchAck\022\020\n\010topic_id\030\001 \001(\r\022\024\n\014partitio" +
      "n_id\030\002 \001(\r\022\021\n\tschema_id\030\003 \001(\r\022\024\n\014start_o" +
      "ffset\030\004 \001(\004\022\022\n\nend_offset\030\005 \001(\004\"b\n\rAppen" +
      "dRequest\022\021\n\twriter_id\030\001 \001(\014\022\022\n\nappend_se" +
      "q\030\002 \001(\004\022*\n\007batches\030\003 \003(\0132\031.turbine.wire." +
      "RecordBatch\"\215\001\n\016AppendResponse\022\022\n\nappend" +
      "_seq\030\001 \001(\004\022\017\n\007success\030\002 \001(\010\022\022\n\nerror_cod" +
      "e\030\003 \001(\r\022\025\n\rerror_message\030\004 \001(\t\022+\n\013append" +
      "_acks\030\005 \003(\0132\026.turbine.wire.BatchAck\"Z\n\rP" +
      "artitionRead\022\020\n\010topic_id\030\001 \001(\r\022\024\n\014partit" +
      "ion_id\030\002 \001(\r\022\016\n\006offset\030\003 \001(\004\022\021\n\tmax_byte" +
      "s\030\004 \001(\r\"r\n\013ReadRequest\022\020\n\010group_id\030\001 \001(\t" +
      "\022\021\n\treader_id\030\002 \001(\t\022\022\n\ngeneration\030\003 \001(\004\022" +
      "*\n\005reads\030\004 \003(\0132\033.turbine.wire.PartitionR" +
      "ead\"\213\001\n\017PartitionResult\022\020\n\010topic_id\030\001 \001(" +
      "\r\022\024\n\014partition_id\030\002 \001(\r\022\021\n\tschema_id\030\003 \001" +
      "(\r\022\026\n\016high_watermark\030\004 \001(\004\022%\n\007records\030\005 " +
      "\003(\0132\024.turbine.wire.Record\"z\n\014ReadRespons" +
      "e\022\017\n\007success\030\001 \001(\010\022\022\n\nerror_code\030\002 \001(\r\022\025" +
      "\n\rerror_message\030\003 \001(\t\022.\n\007results\030\004 \003(\0132\035" +
      ".turbine.wire.PartitionResult\"J\n\020JoinGro" +
      "upRequest\022\020\n\010group_id\030\001 \001(\t\022\021\n\treader_id" +
      "\030\002 \001(\t\022\021\n\ttopic_ids\030\003 \003(\r\"W\n\023PartitionAs" +
      "signment\022\020\n\010topic_id\030\001 \001(\r\022\024\n\014partition_" +
      "id\030\002 \001(\r\022\030\n\020committed_offset\030\003 \001(\004\"\233\001\n\021J" +
      "oinGroupResponse\022\017\n\007success\030\001 \001(\010\022\022\n\nerr" +
      "or_code\030\002 \001(\r\022\025\n\rerror_message\030\003 \001(\t\022\022\n\n" +
      "generation\030\004 \001(\004\0226\n\013assignments\030\005 \003(\0132!." +
      "turbine.wire.PartitionAssignment\"]\n\020Hear" +
      "tbeatRequest\022\020\n\010group_id\030\001 \001(\t\022\020\n\010topic_" +
      "id\030\002 \001(\r\022\021\n\treader_id\030\003 \001(\t\022\022\n\ngeneratio" +
      "n\030\004 \001(\004\"\222\001\n\021HeartbeatResponse\022\017\n\007success" +
      "\030\001 \001(\010\022\022\n\nerror_code\030\002 \001(\r\022\025\n\rerror_mess" +
      "age\030\003 \001(\t\022\022\n\ngeneration\030\004 \001(\004\022-\n\006status\030" +
      "\005 \001(\0162\035.turbine.wire.HeartbeatStatus\"Z\n\r" +
      "RejoinRequest\022\020\n\010group_id\030\001 \001(\t\022\020\n\010topic" +
      "_id\030\002 \001(\r\022\021\n\treader_id\030\003 \001(\t\022\022\n\ngenerati" +
      "on\030\004 \001(\004\"\304\001\n\016RejoinResponse\022\017\n\007success\030\001" +
      " \001(\010\022\022\n\nerror_code\030\002 \001(\r\022\025\n\rerror_messag" +
      "e\030\003 \001(\t\022\022\n\ngeneration\030\004 \001(\004\022*\n\006status\030\005 " +
      "\001(\0162\032.turbine.wire.RejoinStatus\0226\n\013assig" +
      "nments\030\006 \003(\0132!.turbine.wire.PartitionAss" +
      "ignment\"J\n\021LeaveGroupRequest\022\020\n\010group_id" +
      "\030\001 \001(\t\022\020\n\010topic_id\030\002 \001(\r\022\021\n\treader_id\030\003 " +
      "\001(\t\"P\n\022LeaveGroupResponse\022\017\n\007success\030\001 \001" +
      "(\010\022\022\n\nerror_code\030\002 \001(\r\022\025\n\rerror_message\030" +
      "\003 \001(\t\"I\n\017PartitionCommit\022\020\n\010topic_id\030\001 \001" +
      "(\r\022\024\n\014partition_id\030\002 \001(\r\022\016\n\006offset\030\003 \001(\004" +
      "\"x\n\rCommitRequest\022\020\n\010group_id\030\001 \001(\t\022\021\n\tr" +
      "eader_id\030\002 \001(\t\022\022\n\ngeneration\030\003 \001(\004\022.\n\007co" +
      "mmits\030\004 \003(\0132\035.turbine.wire.PartitionComm" +
      "it\"L\n\016CommitResponse\022\017\n\007success\030\001 \001(\010\022\022\n" +
      "\nerror_code\030\002 \001(\r\022\025\n\rerror_message\030\003 \001(\t" +
      "\"\036\n\013AuthRequest\022\017\n\007api_key\030\001 \001(\t\"J\n\014Auth" +
      "Response\022\017\n\007success\030\001 \001(\010\022\022\n\nerror_code\030" +
      "\002 \001(\r\022\025\n\rerror_message\030\003 \001(\t\"\240\003\n\rClientM" +
      "essage\022-\n\006append\030\001 \001(\0132\033.turbine.wire.Ap" +
      "pendRequestH\000\022)\n\004read\030\002 \001(\0132\031.turbine.wi" +
      "re.ReadRequestH\000\0224\n\njoin_group\030\003 \001(\0132\036.t" +
      "urbine.wire.JoinGroupRequestH\000\0223\n\theartb" +
      "eat\030\004 \001(\0132\036.turbine.wire.HeartbeatReques" +
      "tH\000\022-\n\006rejoin\030\005 \001(\0132\033.turbine.wire.Rejoi" +
      "nRequestH\000\0226\n\013leave_group\030\006 \001(\0132\037.turbin" +
      "e.wire.LeaveGroupRequestH\000\022-\n\006commit\030\007 \001" +
      "(\0132\033.turbine.wire.CommitRequestH\000\022)\n\004aut" +
      "h\030\010 \001(\0132\031.turbine.wire.AuthRequestH\000B\t\n\007" +
      "message\"\250\003\n\rServerMessage\022.\n\006append\030\001 \001(" +
      "\0132\034.turbine.wire.AppendResponseH\000\022*\n\004rea" +
      "d\030\002 \001(\0132\032.turbine.wire.ReadResponseH\000\0225\n" +
      "\njoin_group\030\003 \001(\0132\037.turbine.wire.JoinGro" +
      "upResponseH\000\0224\n\theartbeat\030\004 \001(\0132\037.turbin" +
      "e.wire.HeartbeatResponseH\000\022.\n\006rejoin\030\005 \001" +
      "(\0132\034.turbine.wire.RejoinResponseH\000\0227\n\013le" +
      "ave_group\030\006 \001(\0132 .turbine.wire.LeaveGrou" +
      "pResponseH\000\022.\n\006commit\030\007 \001(\0132\034.turbine.wi" +
      "re.CommitResponseH\000\022*\n\004auth\030\010 \001(\0132\032.turb" +
      "ine.wire.AuthResponseH\000B\t\n\007message*v\n\017He" +
      "artbeatStatus\022\027\n\023HEARTBEAT_STATUS_OK\020\000\022%" +
      "\n!HEARTBEAT_STATUS_REBALANCE_NEEDED\020\001\022#\n" +
      "\037HEARTBEAT_STATUS_UNKNOWN_MEMBER\020\002*H\n\014Re" +
      "joinStatus\022\024\n\020REJOIN_STATUS_OK\020\000\022\"\n\036REJO" +
      "IN_STATUS_REBALANCE_NEEDED\020\001B\030\n\024io.turbi" +
      "ne.sdk.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_turbine_wire_Record_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_turbine_wire_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_Record_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_turbine_wire_RecordBatch_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_turbine_wire_RecordBatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_RecordBatch_descriptor,
        new java.lang.String[] { "TopicId", "PartitionId", "SchemaId", "Records", });
    internal_static_turbine_wire_BatchAck_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_turbine_wire_BatchAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_BatchAck_descriptor,
        new java.lang.String[] { "TopicId", "PartitionId", "SchemaId", "StartOffset", "EndOffset", });
    internal_static_turbine_wire_AppendRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_turbine_wire_AppendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_AppendRequest_descriptor,
        new java.lang.String[] { "WriterId", "AppendSeq", "Batches", });
    internal_static_turbine_wire_AppendResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_turbine_wire_AppendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_AppendResponse_descriptor,
        new java.lang.String[] { "AppendSeq", "Success", "ErrorCode", "ErrorMessage", "AppendAcks", });
    internal_static_turbine_wire_PartitionRead_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_turbine_wire_PartitionRead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_PartitionRead_descriptor,
        new java.lang.String[] { "TopicId", "PartitionId", "Offset", "MaxBytes", });
    internal_static_turbine_wire_ReadRequest_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_turbine_wire_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_ReadRequest_descriptor,
        new java.lang.String[] { "GroupId", "ReaderId", "Generation", "Reads", });
    internal_static_turbine_wire_PartitionResult_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_turbine_wire_PartitionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_PartitionResult_descriptor,
        new java.lang.String[] { "TopicId", "PartitionId", "SchemaId", "HighWatermark", "Records", });
    internal_static_turbine_wire_ReadResponse_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_turbine_wire_ReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_ReadResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", "Results", });
    internal_static_turbine_wire_JoinGroupRequest_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_turbine_wire_JoinGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_JoinGroupRequest_descriptor,
        new java.lang.String[] { "GroupId", "ReaderId", "TopicIds", });
    internal_static_turbine_wire_PartitionAssignment_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_turbine_wire_PartitionAssignment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_PartitionAssignment_descriptor,
        new java.lang.String[] { "TopicId", "PartitionId", "CommittedOffset", });
    internal_static_turbine_wire_JoinGroupResponse_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_turbine_wire_JoinGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_JoinGroupResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", "Generation", "Assignments", });
    internal_static_turbine_wire_HeartbeatRequest_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_turbine_wire_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_HeartbeatRequest_descriptor,
        new java.lang.String[] { "GroupId", "TopicId", "ReaderId", "Generation", });
    internal_static_turbine_wire_HeartbeatResponse_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_turbine_wire_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", "Generation", "Status", });
    internal_static_turbine_wire_RejoinRequest_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_turbine_wire_RejoinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_RejoinRequest_descriptor,
        new java.lang.String[] { "GroupId", "TopicId", "ReaderId", "Generation", });
    internal_static_turbine_wire_RejoinResponse_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_turbine_wire_RejoinResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_RejoinResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", "Generation", "Status", "Assignments", });
    internal_static_turbine_wire_LeaveGroupRequest_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_turbine_wire_LeaveGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_LeaveGroupRequest_descriptor,
        new java.lang.String[] { "GroupId", "TopicId", "ReaderId", });
    internal_static_turbine_wire_LeaveGroupResponse_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_turbine_wire_LeaveGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_LeaveGroupResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", });
    internal_static_turbine_wire_PartitionCommit_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_turbine_wire_PartitionCommit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_PartitionCommit_descriptor,
        new java.lang.String[] { "TopicId", "PartitionId", "Offset", });
    internal_static_turbine_wire_CommitRequest_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_turbine_wire_CommitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_CommitRequest_descriptor,
        new java.lang.String[] { "GroupId", "ReaderId", "Generation", "Commits", });
    internal_static_turbine_wire_CommitResponse_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_turbine_wire_CommitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_CommitResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", });
    internal_static_turbine_wire_AuthRequest_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_turbine_wire_AuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_AuthRequest_descriptor,
        new java.lang.String[] { "ApiKey", });
    internal_static_turbine_wire_AuthResponse_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_turbine_wire_AuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_AuthResponse_descriptor,
        new java.lang.String[] { "Success", "ErrorCode", "ErrorMessage", });
    internal_static_turbine_wire_ClientMessage_descriptor =
      getDescriptor().getMessageType(23);
    internal_static_turbine_wire_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_ClientMessage_descriptor,
        new java.lang.String[] { "Append", "Read", "JoinGroup", "Heartbeat", "Rejoin", "LeaveGroup", "Commit", "Auth", "Message", });
    internal_static_turbine_wire_ServerMessage_descriptor =
      getDescriptor().getMessageType(24);
    internal_static_turbine_wire_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_turbine_wire_ServerMessage_descriptor,
        new java.lang.String[] { "Append", "Read", "JoinGroup", "Heartbeat", "Rejoin", "LeaveGroup", "Commit", "Auth", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
